feat: goodbye sms journey
Stand-With-Crypto/swc-web pull request #1021
Opened 2024-06-26 13:01 UTC by LucasdRossi

closes 

fixes 

## What changed? Why?

## PlanetScale deploy request

## Notes to reviewers

## How has it been tested?

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-07-08 14:09 UTC, lucasrmp-cb requested changes

2024-07-08 14:09 UTC, lucasrmp-cb commented on src/actions/actionUpdateUserProfile.ts
> +      .flush()
np: if you're doing only one track you can condense this into one statement
```suggestion
    await getServerAnalytics({
      localUser,
      userId: authUser.userId,
    })
      .track('User SMS Opt-In', {
        provider: 'twilio',
      })
      .flush()
```

2024-07-08 14:09 UTC, lucasrmp-cb commented on src/app/api/public/sms/events/messages/route.ts
> +    await analytics.track('User SMS Unstop').flush()
same np here

2024-07-08 14:09 UTC, lucasrmp-cb commented on src/app/api/public/sms/events/messages/route.ts
> +      .flush()
and here

2024-07-08 14:09 UTC, lucasrmp-cb commented on src/app/api/public/sms/events/messages/route.ts
> +async function optUserBackIn({ phoneNumber, user }: OptUserBackInProps) {
Can we separate this functions into the sms lib? I think this is too much clutter for the route file

2024-07-08 14:09 UTC, lucasrmp-cb commented on src/inngest/functions/capitolCanary/checkSMSOptInReply.ts
> +        .flush()
+1

2024-07-08 14:09 UTC, lucasrmp-cb commented on src/inngest/functions/sms/unstopConfirmationSMSCommunicationJourney.ts
> +    }
Shouldn't we be checking for a valid phone number here? If the user inputs an invalid phone number I think we should throw this error instead of the 500 that will prob happen when sendgrid tries to send the sms

2024-07-08 17:03 UTC, lucasrmp-cb approved these changes

2024-07-08 17:03 UTC, lucasrmp-cb commented on src/app/api/public/sms/events/messages/route.ts
> +        await optOutUser(phoneNumber, keyword === SWC_STOP_SMS_KEYWORD, user)
Didn't get this `keyword === SWC_STOP_SMS_KEYWORD` statement, we're inside a case where this is always true, no?

2024-07-08 17:16 UTC, LucasdRossi commented on src/app/api/public/sms/events/messages/route.ts
> +        await optOutUser(phoneNumber, keyword === SWC_STOP_SMS_KEYWORD, user)
Not in this scenario, because the case statements above have no break, so line 71 will be executed if the keyword is: "STOPALL" or "UNSUBSCRIBE" or "CANCEL" or ... or SWC_STOP_SMS_KEYWORD

```javascript
const keyword = "STOP"

switch(keyword) {
    case "STOP":
    case "SWC_STOP":
        console.log(keyword === "SWC_STOP") // this will print false
        break
    default:
        break
}
```

2024-07-08 18:42 UTC, lucasrmp-cb submitted a review, later dismissed

2024-07-09 12:45 UTC, lucasrmp-cb approved these changes

2024-07-09 12:51 UTC, merged