feat: bulk sms journey
Stand-With-Crypto/swc-web pull request #1055
Opened 2024-07-10 19:07 UTC by LucasdRossi

closes 

fixes 

## What changed? Why?

## PlanetScale deploy request

## Notes to reviewers

## How has it been tested?

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-07-11 13:14 UTC, travisbloom-cb requested changes

2024-07-11 13:14 UTC, travisbloom-cb commented on src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
> +      const phoneNumbers = await prismaClient.user.groupBy({
prisma limits to 100k rows in queries so you might need to paginate your queries

2024-07-11 13:14 UTC, travisbloom-cb commented on src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
> +          step.run(`send-sms-${batchNum}:${index + 1}`, async () => {
this could get expensive at scale (https://www.inngest.com/pricing?ref=nav) if we're sending texts to 500k+ users at once. We might want to rethink where we use steps

2024-07-11 13:14 UTC, travisbloom-cb commented on src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
> +      await step.sleep(`script.sleep-${batchNum}`, 1000 * segmentsCount)
Why?

2024-07-11 13:14 UTC, travisbloom-cb commented on src/inngest/functions/sms/shared/validatePhoneNumber.ts
> +  const lookup = await messagingClient.lookups.v2.phoneNumbers(phoneNumber).fetch()
This is super pricey https://www.twilio.com/en-us/verify/pricing. We prob want to track if texting a number fails (because its an invalid number), and then flag in the db that the number shouldnt be texted. Rather than always validating using this API

2024-07-11 13:39 UTC, LucasdRossi commented on src/inngest/functions/sms/shared/validatePhoneNumber.ts
> +  const lookup = await messagingClient.lookups.v2.phoneNumbers(phoneNumber).fetch()
The lookup API is free https://www.twilio.com/en-us/user-authentication-identity/pricing/lookup. We'll only get charged if we use additional features like: Inbound caller identification, Identity match and Reassigned number risk.

2024-07-11 13:53 UTC, LucasdRossi commented on src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
> +      await step.sleep(`script.sleep-${batchNum}`, 1000 * segmentsCount)
With an MPS of 3 Twilio will send 3 segments each second, so if the message has more than one segment we need to wait for all segments to be sent before putting another SMS in queue. We need to do this because we're using a toll-free number and it has max queue of 108,000 so if we don't take the number of segments in consideration and keep adding SMS to the queue, the queue will get full and messages won't be send.

I'll add a comment explaining this

2024-07-11 13:56 UTC, LucasdRossi commented on src/inngest/functions/sms/shared/validatePhoneNumber.ts
> +  const lookup = await messagingClient.lookups.v2.phoneNumbers(phoneNumber).fetch()
I agree that we should flag invalid numbers in the db, but how should we do it?
1. Set smsStatus to NOT_OPTED_IN; or
2. Add a new enum to the smsStatus field; or
3. Add a new flag to the user's table; or
4. Clear the phoneNumber input?

2024-07-11 14:04 UTC, LucasdRossi commented on src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
> +          step.run(`send-sms-${batchNum}:${index + 1}`, async () => {
Ok, maybe we should fill the queue, wait for it to be empty and repeat this until there are no more messages. This way we would reduce the number of steps. What do you think?

2024-07-16 21:55 UTC, LucasdRossi commented on src/inngest/functions/sms/shared/validatePhoneNumber.ts
> +  const lookup = await messagingClient.lookups.v2.phoneNumbers(phoneNumber).fetch()
Created a new issue to work on this [#90](https://github.com/Stand-With-Crypto/swc-internal/issues/90)

2024-07-18 14:54 UTC, travisbloom-cb submitted a review, later dismissed

2024-07-18 14:54 UTC, travisbloom-cb commented on src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
> +        // count() with distinct: not supported https://github.com/prisma/prisma/issues/4228. Would need a workaround that doesn't support custom userWhereInput
we could just write a `prisma.rawQuery` for count distinct? Fine either way if this works

2024-07-18 14:54 UTC, travisbloom-cb commented on src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
> +import { Prisma, SMSStatus, User, UserCommunicationJourneyType } from '@prisma/client'
I wonder if we could break some of the computation logic in to unit-testable functions

2024-07-18 17:01 UTC, LucasdRossi commented on src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
> +        // count() with distinct: not supported https://github.com/prisma/prisma/issues/4228. Would need a workaround that doesn't support custom userWhereInput
Yes we could, but then we wouldn't be able to take in count the userWhereInput, because it's a prisma object.

2024-07-18 17:09 UTC, lucasrmp-cb commented on src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
> +  }
We have a seconds duration shared constant for this kind of comparison
```suggestion
  if (seconds < SECONDS_DURATION.MINUTE) {
    return `${seconds.toPrecision(2)} seconds`
  } else if (seconds < SECONDS_DURATION.HOUR) {
    // less than 60 minutes (3600 seconds)
    const minutes = Math.ceil(seconds / SECONDS_DURATION.MINUTE)
    return `${minutes} minutes`
  } else if (seconds < SECONDS_DURATION.DAY) {
    // less than 24 hours (86400 seconds)
    const hours = Math.ceil(seconds / SECONDS_DURATION.HOUR)
    return `${hours} hours`
  } else {
    // 24 hours or more
    const days = Math.ceil(seconds / SECONDS_DURATION.DAY)
    return `${days} days`
  }
```

2024-07-18 17:38 UTC, travisbloom-cb commented on src/inngest/functions/sms/bulkSMSCommunicationJourney.ts
> +  smsBody: string
we'll want a persist flag as well so we can run this and log out how many people are gonna get texted without actually triggering (to audit before sending)

2024-07-19 12:41 UTC, lucasrmp-cb approved these changes

2024-07-19 14:05 UTC, travisbloom-cb approved these changes

2024-07-22 12:27 UTC, merged