Append congressional district metadata to users address
Stand-With-Crypto/swc-web pull request #1056
Opened 2024-07-10 23:53 UTC by mhamendes

closes #774 

fixes 

## What changed? Why?

- Append congressional district metadata to address on address creation or update.
- Script to backfill all addresses with congressional metadata using a zipcode to district number json file or using the google civic api as fallback

## How has it been tested?

- [x] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-07-11 12:53 UTC, travisbloom-cb requested changes

2024-07-11 12:53 UTC, travisbloom-cb commented on src/actions/actionCreateUserActionCallCongressperson/index.ts
> +    logger.error('error getting `usCongressionalDistrict`:' + e)
prob want to log to sentry if it's an unexpected `notFoundReason`: CIVIC_API_DOWN or UNEXPECTED_ERROR

2024-07-11 12:53 UTC, travisbloom-cb commented on src/actions/actionCreateUserActionCallCongressperson/index.ts
> +    const usCongressionalDistrict = await getCongressionalDistrictFromAddress(
we can also prob have some basic logic that checks if its a US address before hitting the civic API

2024-07-11 12:53 UTC, travisbloom-cb commented on src/actions/actionCreateUserActionEmailCongressperson.ts
> +    const usCongressionalDistrict = await getCongressionalDistrictFromAddress(
see comments above, there's prob an abstracted "maybeGetCongressionalDistrictFromAddress" that includes all the address fields, not just formatted description (because we have it on the backend)

2024-07-11 12:53 UTC, travisbloom-cb commented on src/bin/backfillMissingUsCongressionalDistricts.ts
> +  fs.readFileSync('src/bin/CongressionalDistrict.json', 'utf8'),
where did we get this? We might want to axe the zipcode idea, see [this thread](https://coinbase.slack.com/archives/C074HPDK067/p1716347101555329). Open to pushback (i agree it would be way more efficient :( )

2024-07-11 13:06 UTC, travisbloom-cb commented
We'll also want this to be an inngest fn (or have an inngest fn that calls this) so we can run the backfill in prod with some cron cadence

2024-07-19 14:03 UTC, travisbloom-cb commented on src/actions/actionCreateUserActionCallCongressperson/index.ts
> +    logger.error('error getting `usCongressionalDistrict`:' + e)
I think we're still missing this right?

2024-07-24 22:51 UTC, lucasrmp-cb submitted a review, later dismissed

2024-07-25 13:45 UTC, travisbloom-cb approved these changes

2024-07-25 18:22 UTC, merged