Creates `working with two or more campaigns active` documentation
Stand-With-Crypto/swc-web pull request #1067
Opened 2024-07-15 14:12 UTC by twistershark

closes #1012 

## What changed? Why?

This PR creates a new documentation related to having two or more campaigns active at the same type for the same user action.

2024-07-17 17:22 UTC, olavoparno submitted a review, later dismissed

2024-07-17 17:38 UTC, lucasrmp-cb requested changes

2024-07-17 17:38 UTC, lucasrmp-cb commented on docs/Working with two or more campaigns active.md
> +- You need to create all the necessary UI components, dialogs, deeplink page, server actions, and any other elements required for the new campaign to function correctly. Use any user action as an exa
We can link to [this](https://github.com/Stand-With-Crypto/swc-web/blob/143be6df65728edf197abe2ba2da57a8ad379e69/docs/Add%20a%20new%20user%20action.md) here:

2024-07-17 17:51 UTC, lucasrmp-cb commented on docs/Working with two or more campaigns active.md
> +- You need to create all the necessary UI components, dialogs, deeplink page, server actions, and any other elements required for the new campaign to function correctly. Use any user action as an exa
And also I think it'd be nice to link this doc for multiple campaigns in the one about creating new actions too

2024-07-17 20:55 UTC, twistershark commented on docs/Working with two or more campaigns active.md
> +- You need to create all the necessary UI components, dialogs, deeplink page, server actions, and any other elements required for the new campaign to function correctly. Use any user action as an exa
Updated!

2024-07-17 20:58 UTC, olavoparno submitted a review, later dismissed

2024-07-17 21:00 UTC, olavoparno submitted a review, later dismissed

2024-07-18 09:25 UTC, lucasrmp-cb approved these changes

2024-07-26 12:28 UTC, olavoparno approved these changes

2024-07-26 12:49 UTC, merged