WIP: Log Vercel geo
Stand-With-Crypto/swc-web pull request #1073
Opened 2024-07-16 20:38 UTC by eduardopicolo-cb

closes 

fixes 

## What changed? Why?

## PlanetScale deploy request

## Notes to reviewers

## How has it been tested?

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-07-22 17:56 UTC, travisbloom-cb reviewed
This looks great!

2024-07-22 17:56 UTC, travisbloom-cb commented on src/components/app/geoGate.tsx
> +  if (!hasHydrated) return children
🙌

2024-07-22 17:56 UTC, travisbloom-cb commented on src/components/app/userActionFormCommon/actionUnavailable.tsx
> +export const UserActionFormActionUnavailable = (props: UserActionFormActionUnavailableProps) => {
Lets trigger an analytics event every time this is displayed

2024-07-22 17:56 UTC, travisbloom-cb commented on src/components/app/userActionFormCommon/dialog.tsx
> +    <Dialog {...dialogProps} analytics={ANALYTICS_NAME_USER_ACTION_FORM_UNAVAILABLE}>
Is there a reason we're rendering different dialogs? could we reduce jank if we have the Geogate nested in the parent dialog?

2024-07-22 17:56 UTC, travisbloom-cb commented on src/utils/server/setCookie.ts
> +export async function setCookie(...args: Parameters<ReturnType<typeof cookies>['set']>) {
are we using?

2024-07-22 17:56 UTC, travisbloom-cb commented on src/utils/server/userActionValidation/checkCountryCode.ts
> +  return async () => {
any reason this is async?

2024-07-22 18:52 UTC, lucasrmp-cb reviewed
Looking good

2024-07-22 18:52 UTC, lucasrmp-cb commented on src/components/app/userActionFormCallCongressperson/sections/suggestedScript.tsx
> +            toastGenericError()
If this `if` condition is met you're showing 2 toasts, don't think this is expected

2024-07-22 18:52 UTC, lucasrmp-cb commented on src/components/app/userActionFormNFTMint/sections/transactionWatch.tsx
> +          toastGenericError()
Same problem with duplicated toasts here

2024-07-22 18:52 UTC, lucasrmp-cb commented on src/utils/server/setCookie.ts
> +export async function setCookie(...args: Parameters<ReturnType<typeof cookies>['set']>) {
Unnecessary abstraction IMO

2024-07-22 19:00 UTC, eduardopicolo-cb commented on src/utils/server/setCookie.ts
> +export async function setCookie(...args: Parameters<ReturnType<typeof cookies>['set']>) {
Yes, for the /internal/user-config page

2024-07-22 19:02 UTC, eduardopicolo-cb commented on src/utils/server/userActionValidation/checkCountryCode.ts
> +  return async () => {
Its a server-action, so it has to be async otherwise nextjs throws an error

2024-07-22 19:11 UTC, eduardopicolo-cb commented on src/utils/server/setCookie.ts
> +export async function setCookie(...args: Parameters<ReturnType<typeof cookies>['set']>) {
Due to be `cookies` being a dynamic function, it cannot be directly imported in a client component:
`Error: 
  × You're importing a component that needs next/headers. That only works in a Server Component but one of its parents is marked with "use client"`
  
This is only being used internally though.

2024-07-23 21:17 UTC, lucasrmp-cb commented on src/components/app/pageDonate/donateButton.tsx
> +          }
We still want to toast a generic error when this doesn't match, but it should be an `else` statement or you should have a return in this block

2024-07-23 21:17 UTC, lucasrmp-cb commented on src/components/app/userActionFormCallCongressperson/sections/suggestedScript.tsx
> +            } else toastGenericError()
Like this

2024-07-23 21:19 UTC, lucasrmp-cb requested changes
Comments above

2024-07-24 14:42 UTC, travisbloom-cb commented on src/utils/server/userActionValidation/withValidations.ts
> +      const result = await validation(args)
we should probably:
- throw errors here
- log to sentry

2024-07-24 20:09 UTC, travisbloom-cb reviewed
@eduardopicolo-cb doesn't this mean we won't show a descriptive error anymore?

2024-07-24 20:13 UTC, eduardopicolo-cb commented
> @eduardopicolo-cb doesn't this mean we won't show a descriptive error anymore?

We won't. But a geo gated client should never be able to trigger an action

2024-07-25 13:28 UTC, travisbloom-cb approved these changes

2024-07-25 14:52 UTC, merged