WIP: Migrate Thirdweb to V5
Stand-With-Crypto/swc-web pull request #1079
Opened 2024-07-18 20:46 UTC by twistershark

closes #773 

## What changed? Why?

This PR migrates the codebase to work with thirdweb on V5.

## How has it been tested?

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-07-26 13:05 UTC, olavoparno commented on src/components/app/userActionFormCommon/nftDisplay.tsx
> +  const image = isThirdwebMedia ? (
i'd just try avoiding nested ternaries here man, maybe abstracting it into a function getImage with early returns

2024-07-26 13:09 UTC, olavoparno commented on src/components/app/authentication/loginDialogWrapper.tsx
> +          <DialogTitle>
does it even make sense having DialogTitle or any other non primitive tags inside VisuallyHidden? just wondering if I got it right

2024-07-26 13:27 UTC, olavoparno approved these changes

2024-07-26 13:28 UTC, olavoparno commented
nice work, man

2024-07-26 16:50 UTC, twistershark commented on src/components/app/userActionFormCommon/nftDisplay.tsx
> +  const image = isThirdwebMedia ? (
Fixed!

2024-07-26 16:52 UTC, twistershark commented on src/components/app/authentication/loginDialogWrapper.tsx
> +          <DialogTitle>
The idea here is to remove the error message related to accessibility and missing the DialogTitle inside DialogContent.

To prevent showing the DialogTitle, I'm using this VisuallyHidden component from RadixUI to hide it for normal users, but allow the content to be read by screen readers

2024-07-26 16:53 UTC, olavoparno submitted a review, later dismissed

2024-07-26 18:16 UTC, lucasrmp-cb requested changes
Looking good

2024-07-26 18:16 UTC, lucasrmp-cb commented on src/components/app/userActionFormNFTMint/useCheckoutController.ts
> +  const gasNumberInBigNumber = BigNumber.from(0).add(gasFee ?? 0)
wouldn't `BigNumber.from(gasFee)` work?

2024-07-26 18:16 UTC, lucasrmp-cb commented on src/components/app/userActionFormNFTMint/useCheckoutController.ts
> +    const tx = claimTo({ contract, quantity: BigInt(quantity), to: account?.address ?? '' })
Is this actually creating the transaction or is it just preparing it?

2024-07-26 18:16 UTC, lucasrmp-cb commented on src/hooks/useAuthUser.ts
> +  const { userId, address } = decodedToken?.ctx ?? {}
This should be inside a `useMemo`, we're doing a cookie get and a jwt decode, we don't want to do it on every render

2024-07-26 18:16 UTC, lucasrmp-cb commented on src/hooks/useENS.ts
> +  return useSWR(address, async () => await getData(address))
Not the optimal way to do this, we don't need to access `address` from the scope inside the fetcher function
```suggestion
  return useSWR(user?.address, getData)
```
What you pass to the first arg of `useSWR` is passed as arg to the fetcher fn, so just passing getData would access the value in the way `swr` intends

2024-07-26 18:16 UTC, lucasrmp-cb commented on src/hooks/useSendMintNFTTransaction.ts
> +  })
Don't know what this does, but smells to me like it should be in a `useMemo`

2024-07-26 18:40 UTC, twistershark commented on src/components/app/userActionFormNFTMint/useCheckoutController.ts
> +  const gasNumberInBigNumber = BigNumber.from(0).add(gasFee ?? 0)
Actually it doesn't. We can't just use `BigNumber.from(gasFee)` because they expect a number or string for the from method and gasFee is a bigint. Strangely, add accepts bigint. So the idea here is to create a new BigNumber instance as zero and then adding the gasFee(bigint) value

2024-07-26 18:42 UTC, twistershark commented on src/hooks/useSendMintNFTTransaction.ts
> +  })
This function is a replacement for the old useContract hook, allowing us to get contract information without needing to be inside a component or hook

2024-07-29 15:25 UTC, twistershark commented on src/hooks/useSendMintNFTTransaction.ts
> +  })
Added the useMemo

2024-07-29 15:26 UTC, twistershark commented on src/hooks/useENS.ts
> +  return useSWR(address, async () => await getData(address))
Thanks for the suggestion! Updated!

2024-07-29 15:27 UTC, twistershark commented on src/hooks/useAuthUser.ts
> +  const { userId, address } = decodedToken?.ctx ?? {}
Updated

2024-07-29 15:29 UTC, twistershark commented on src/components/app/userActionFormNFTMint/useCheckoutController.ts
> +    const tx = claimTo({ contract, quantity: BigInt(quantity), to: account?.address ?? '' })
Just preparing the transaction to get the current gasFee price, but we don't use this prepared transaction afterwards as we recreate it again on the `onMint` function that actually prepares the transaction to be executed

2024-07-29 22:14 UTC, lucasrmp-cb commented on src/hooks/useAuthUser.ts
> +  }, [token])
I think we merged two possible solution we discussed here, not sure that both are necessary, try one of these:
```suggestion
  const loginStatus = useActiveWalletConnectionStatus()

  const { userId, address } = useMemo(() => {
    const token = Cookies.get(THIRDWEB_AUTH_TOKEN_COOKIE_PREFIX)
    const decodedToken = token
      ? jwtDecode<{ ctx?: { userId?: string; address?: string } }>(token)
      : null
    const { userId, address } = decodedToken?.ctx ?? {}

    return { userId, address }
  }, [loginStatus])
```

**OR**

```suggestion
  const token = Cookies.get(THIRDWEB_AUTH_TOKEN_COOKIE_PREFIX)

  const { userId, address } = useMemo(() => {
    const decodedToken = token
      ? jwtDecode<{ ctx?: { userId?: string; address?: string } }>(token)
      : null
    const { userId, address } = decodedToken?.ctx ?? {}

    return { userId, address }
  }, [token])
```

2024-07-29 22:14 UTC, lucasrmp-cb commented on src/hooks/useAuthUser.ts
> +  }, [token])
Both of them simplify this code in a different way. If neither work please add a comment to the `useActiveWalletConnectionStatus` call explaining why we aren't using the return value

2024-07-30 12:49 UTC, twistershark commented on src/hooks/useAuthUser.ts
> +  }, [token])
I can't use the `loginStatus` as a dependency on useMemo because React detects that it is not necessary and causes error on the lint verification step. I added a comment with why we are using this `useActiveWalletConnectionStatus` hook without the returned values.

2024-07-30 14:43 UTC, olavoparno submitted a review, later dismissed

2024-07-30 15:16 UTC, lucasrmp-cb approved these changes

2024-07-30 15:40 UTC, olavoparno submitted a review, later dismissed

2024-07-30 15:42 UTC, olavoparno approved these changes

2024-07-30 16:51 UTC, merged