Events page BuilderIO integration
Stand-With-Crypto/swc-web pull request #1162
Opened 2024-08-07 18:13 UTC by twistershark

## What changed? Why?

This PR integrates the events page with builder.io

## How has it been tested?

- [x] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-08-08 19:22 UTC, lucasrmp-cb requested changes

2024-08-08 19:22 UTC, lucasrmp-cb commented on src/app/[locale]/events/[state]/[eventSlug]/page.tsx
Do we really need the state for this? Since the slug is pseudo-unique, can't we make this route `/events/[eventSlug]`?

2024-08-08 19:22 UTC, lucasrmp-cb commented on src/app/[locale]/events/[state]/[eventSlug]/page.tsx
> +  }
I think we want a sentry log or a 404 page here (I lean towards a sentry log)

2024-08-08 19:22 UTC, lucasrmp-cb commented on src/app/[locale]/events/[state]/[eventSlug]/page.tsx
> +export default async function EventDetailsPageRoot({ params }: Props) {
Can this page be static with a revalidate?

2024-08-08 19:22 UTC, lucasrmp-cb commented on src/app/[locale]/events/[state]/page.tsx
Realizing that `/events/[eventSlug]` would clash with this, but I'd rather change this to `/events/by-state/[state]` (or something like that), that way the vanity url for the event details page would be cleaner

2024-08-08 19:22 UTC, lucasrmp-cb commented on src/app/[locale]/events/[state]/page.tsx
> +  }
Let's add a sentry log here

2024-08-08 19:22 UTC, lucasrmp-cb commented on src/app/[locale]/events/[state]/page.tsx
> +export default async function StateEventsPageRoot({ params }: Props) {
Same point on making this static with a revalidate, we usually want to reduce CMS calls as much as possible, having these pages with `revalidate` makes so we don't do one builder io request per user access

2024-08-08 19:22 UTC, lucasrmp-cb commented on src/app/[locale]/events/page.tsx
> +  }
lets add a sentry log here too

2024-08-08 19:22 UTC, lucasrmp-cb commented on src/app/[locale]/events/page.tsx
> +    return NotFound()
We should use the `notFound()` function from `react/navigation` here, not this one

2024-08-08 19:22 UTC, lucasrmp-cb commented on src/app/[locale]/events/page.tsx
> +  return <EventsPage events={events!} />
np: is this `!` necessary?

2024-08-08 19:32 UTC, olavoparno approved these changes

2024-08-08 21:16 UTC, twistershark commented on src/app/[locale]/events/[state]/[eventSlug]/page.tsx
Actually it won't be unique because of that builder up limitation. I'm using the state to try to be more specific

2024-08-08 21:23 UTC, twistershark commented on src/app/[locale]/events/page.tsx
> +  return <EventsPage events={events!} />
Yes... even though I checked above if it was not null, TS was still complaining, but at this point we are sure that it is not null

2024-08-08 21:25 UTC, twistershark commented on src/app/[locale]/events/[state]/page.tsx
Decided to used the state to try to make is a bit more specific, trying to overcome the builder up slug limitation. This way, if we had the same even happening on two states, if the admin reused the same slug, at least the state in the router would help making it load the correct event. But I can change this no problem. I'm fine with whatever

2024-08-09 11:36 UTC, twistershark commented on src/app/[locale]/events/page.tsx
> +    return NotFound()
Updated!

2024-08-09 11:37 UTC, twistershark commented on src/app/[locale]/events/page.tsx
> +  }
Do we need to manually add it here? Because our not-found page already sends this event to Sentry

2024-08-09 11:42 UTC, twistershark commented on src/app/[locale]/events/[state]/page.tsx
> +export default async function StateEventsPageRoot({ params }: Props) {
Updated

2024-08-09 11:43 UTC, twistershark commented on src/app/[locale]/events/[state]/page.tsx
> +  }
Instead or redirecting, I decided to render the notFound which already has the sentry log

2024-08-09 11:44 UTC, twistershark commented on src/app/[locale]/events/[state]/[eventSlug]/page.tsx
> +export default async function EventDetailsPageRoot({ params }: Props) {
Updated

2024-08-09 11:50 UTC, lucasrmp-cb approved these changes

2024-08-09 11:58 UTC, merged