Feat/add reactivation email and backfill
Stand-With-Crypto/swc-web pull request #1171
Opened 2024-08-09 15:15 UTC by olavoparno

closes  https://github.com/Stand-With-Crypto/swc-web/issues/1109

## What changed? Why?

## PlanetScale deploy request

## Notes to reviewers

## How has it been tested?

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-08-09 23:50 UTC, mhamendes commented on src/inngest/functions/backfillReactivation/index.ts
> +  },
Did you confirm that this backfill completes before the function times out? If I am not mistaken, Vercel serverless functions times out after 90s.

2024-08-10 01:16 UTC, olavoparno commented on src/inngest/functions/backfillReactivation/index.ts
> +  },
I haven't thought of that to be honest. The worst case scenario I think is having to run it again, but I'll take a deeper look at it. Thanks man

2024-08-15 16:12 UTC, lucasrmp-cb requested changes

2024-08-15 16:12 UTC, lucasrmp-cb commented on src/utils/server/email/templates/reactivationReminder.tsx
> +          >
2 things:
- We should always use react-email's built in components whenever possible, and they have a anchor component called `Link`
- We should always use `buildTemplateInternalUrl` for links inside stand with crypto, so this would end up like this
```suggestion
          <Link className="text-inherit underline" href={buildTemplateInternalUrl('/', hydratedHrefSearchParams)}>
            our website
          </Link>
```

2024-08-15 16:20 UTC, olavoparno commented on src/utils/server/email/templates/reactivationReminder.tsx
> +          >
thank you man, I've adjusted!

2024-08-15 16:21 UTC, lucasrmp-cb approved these changes

2024-08-15 17:33 UTC, merged