Creates Event notification logic
Stand-With-Crypto/swc-web pull request #1174
Opened 2024-08-09 17:02 UTC by twistershark

## What changed? Why?

## How has it been tested?

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-08-12 20:34 UTC, olavoparno submitted a review, later dismissed

2024-08-12 20:40 UTC, mhamendes commented on src/components/app/pageEvents/components/eventDialogContent.tsx
> +    })
Here is what we talked about making it async. Just change to:

```suggestion
    void handleCreateRsvpAction({
      shouldReceiveNotifications: false,
    })
```

This will trigger the create action but will not block the code.

2024-08-12 20:40 UTC, mhamendes commented on src/components/app/pageEvents/components/eventsMap.tsx
> +'use client'
We should probably create a generic component for the map in the future so we don't have to copy paste the entire map logic when we need to add it to another component and with other data.

2024-08-12 20:40 UTC, mhamendes commented on src/components/app/pageEvents/components/stateEventsDialogContent.tsx
> +        {stateEvents && stateEvents?.length > 0 && (
This should be enough:

```suggestion
        {stateEvents?.length && (
```

2024-08-12 20:40 UTC, mhamendes commented on src/inngest/functions/eventNotification/logic.ts
> +    })
Prisma limits the amount of rows to 100k. If that is a case where we have more than 100k events to notify, this will break. In other cases we create batches to do it.

2024-08-12 20:40 UTC, mhamendes commented on src/inngest/functions/eventNotification/index.ts
> +    })
Its only one step on this run. Vercel has a limit of 3 minutes for a serverless function to resolve, if it takes longer than that, it will break.

2024-08-12 22:55 UTC, twistershark commented on src/components/app/pageEvents/components/eventsMap.tsx
> +'use client'
This is actually something I talked about with Olavo. We will do this refactor in the future, but doing it in this PR would create too much information at the same PR. Great suggestion!

2024-08-12 22:56 UTC, twistershark commented on src/inngest/functions/eventNotification/logic.ts
> +    })
Totally agree. This is something I talked with Bernardo about and I think that for now we should be fine as I don't think that we will have more than 100k notifications to send per event

2024-08-12 23:52 UTC, lucasrmp-cb commented on src/components/app/pageEvents/components/stateEventsDialogContent.tsx
> +        {stateEvents && stateEvents?.length > 0 && (
![image](https://github.com/user-attachments/assets/20c6066e-0585-4151-b373-e36f8fd44d58)
Don't do that, `stateEvents?.length > 0` is the most compact and safe way to do it

2024-08-13 00:58 UTC, mhamendes commented on src/components/app/pageEvents/components/stateEventsDialogContent.tsx
> +        {stateEvents && stateEvents?.length > 0 && (
You are right, did not see we were using logical values for rendering. This is a big issue with using logical operators for rendering stuff, way too common of a mistake when using non boolean values. I would rather always using `condigiton ? component : null` when conditionally rendering components because you avoid falling on this trap.

2024-08-13 12:14 UTC, twistershark commented on src/components/app/pageEvents/components/eventDialogContent.tsx
> +    })
Updated!

2024-08-13 12:17 UTC, twistershark commented on src/components/app/pageEvents/components/stateEventsDialogContent.tsx
> +        {stateEvents && stateEvents?.length > 0 && (
Ok!

2024-08-13 12:24 UTC, twistershark commented on src/inngest/functions/eventNotification/index.ts
> +    })
This function in specific get all events created in builder.io, then filters them in two groups and then, for each event, get all records of notifications for that specific event in our DB and then calls another inngest function to send the SMSs. 

Thinking about a real life scenario here, I don't think that we will have so many events happening on the same day to create a bottleneck here and even so, the bulk SMS function is what could take longer, but we already have logic there to handle with batches when needed and so on.

As a bunch of our inngest functions only have one step and the only async calls that we use in this function is getting builder.io data that happens in less than a second and querying the database that won't take more than a few seconds because I added an index on the eventSlug and eventState that are the two informations that we use to query data, I don't think that this scenario will happen, at least for now.

2024-08-13 12:26 UTC, twistershark commented on src/inngest/functions/eventNotification/logic.ts
> +    })
As we only create a notification record for each user / event, this prob won't be an issue when we compare with our current website traffic. For this to be an issue, we would need to have 100k users creating the notifications alert for an specific event. We should monitor this, but for now I would just ignore it

2024-08-13 16:56 UTC, mhamendes commented on src/inngest/functions/eventNotification/index.ts
> +    })
Oh, in that case everything should be fine, I thought you were sending the notification sms here, if that is not the case, it really should not be an issue.

2024-08-13 16:57 UTC, mhamendes submitted a review, later dismissed

2024-08-13 18:22 UTC, mhamendes commented on src/components/app/pageEvents/components/stateEventsDialogContent.tsx
> +    : []
This should do the trick.

```suggestion
  const stateEvents = events?.filter(event => event.data.state?.toLowerCase() === state.toLowerCase()) ?? []
```

2024-08-13 18:25 UTC, mhamendes submitted a review, later dismissed

2024-08-13 18:29 UTC, lucasrmp-cb requested changes

2024-08-13 18:29 UTC, lucasrmp-cb commented on src/components/app/pageEvents/components/eventDialogPhoneNumber.tsx
> +            <div className="flex w-[84px] items-center justify-center rounded-md border border-input bg-background px-2 py-[15px] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ri
same with `w-[84px]` and `py-[15px]`, lets use close theme values

2024-08-13 18:29 UTC, lucasrmp-cb commented on src/components/app/pageEvents/components/eventDialogPhoneNumber.tsx
> +      <p className="text-center font-mono text-[10px] text-muted-foreground">
same for `text-[10px]`

2024-08-13 18:29 UTC, lucasrmp-cb commented on src/components/app/pageEvents/components/eventsIntro.tsx
> +        <PageTitle className="text-center font-sans text-xl text-foreground lg:text-[2rem]">
same for `text-[2rem]`, lets find a default size that works here

2024-08-13 18:29 UTC, lucasrmp-cb commented on src/inngest/functions/eventNotification/index.ts
> +    })
Got why the timeout is not an issue, but the step is unnecessary, why have this step at all and not just calling the function normally?

2024-08-13 18:36 UTC, twistershark commented on src/components/app/pageEvents/components/allUpcomingEvents.tsx
> +        <div className="flex items-center justify-center gap-4 rounded-[8px] bg-backgroundAlternate px-4 py-3">
Removed

2024-08-13 18:37 UTC, twistershark commented on src/components/app/pageEvents/components/eventDialog.tsx
> +      <DialogTrigger className={triggerClassName ?? 'flex w-full justify-center'}>
The idea is to use triggerClassName or the other, but not both at the same time

2024-08-13 18:38 UTC, twistershark commented on src/components/app/pageEvents/components/eventDialog.tsx
> +        className="max-w-[578px]"
Updated

2024-08-13 18:39 UTC, twistershark commented on src/components/app/pageEvents/components/eventDialogContent.tsx
> +          toast.error(error.message, {
Updated

2024-08-13 18:42 UTC, twistershark commented on src/components/app/pageEvents/components/eventDialogPhoneNumber.tsx
> +            <div className="flex w-[84px] items-center justify-center rounded-md border border-input bg-background px-2 py-[15px] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ri
Changed the w-84px, but i need the padding vertical to be specifically 15px. Can't change that

2024-08-13 18:42 UTC, twistershark commented on src/components/app/pageEvents/components/eventDialogPhoneNumber.tsx
> +      <p className="text-center font-mono text-[10px] text-muted-foreground">
Updated

2024-08-13 18:43 UTC, twistershark commented on src/components/app/pageEvents/components/eventsIntro.tsx
> +        <PageTitle className="text-center font-sans text-xl text-foreground lg:text-[2rem]">
Updated

2024-08-13 18:46 UTC, twistershark commented on src/components/app/pageEvents/components/eventDialogContent.tsx
> +  async function handleCreateRsvpAction({
Updated

2024-08-13 18:50 UTC, twistershark commented on src/components/app/pageEvents/components/allUpcomingEvents.tsx
> +          <div className="h-[2rem] w-[1px] bg-[#D8DCE2]" />
updated

2024-08-13 19:02 UTC, lucasrmp-cb approved these changes

2024-08-13 19:34 UTC, mhamendes commented on src/components/app/pageEvents/components/stateEventsDialog.tsx
> +    analytics: `${US_MAIN_STATE_CODE_TO_DISPLAY_NAME_MAP[state?.toUpperCase() as keyof typeof US_MAIN_STATE_CODE_TO_DISPLAY_NAME_MAP]} Events Dialog`,
If state is null or undefined this will break because null and undefined cannot index a object.

2024-08-13 19:38 UTC, twistershark commented on src/components/app/pageEvents/components/stateEventsDialog.tsx
> +    analytics: `${US_MAIN_STATE_CODE_TO_DISPLAY_NAME_MAP[state?.toUpperCase() as keyof typeof US_MAIN_STATE_CODE_TO_DISPLAY_NAME_MAP]} Events Dialog`,
This won't ever happen because on the deeplink page we check if the state is present and valid, and we parse all builder.io information as well, so if the state is null|undefined(it is a required field on builder.io) it would just not show on the events page

2024-08-13 20:03 UTC, mhamendes approved these changes

2024-08-13 20:17 UTC, lucasrmp-cb submitted a review, later dismissed

2024-08-13 22:35 UTC, mhamendes approved these changes

2024-08-13 22:59 UTC, olavoparno approved these changes

2024-08-13 23:01 UTC, olavoparno submitted a review, later dismissed

2024-08-14 01:02 UTC, lucasrmp-cb submitted a review, later dismissed

2024-08-14 01:27 UTC, mhamendes approved these changes

2024-08-14 01:28 UTC, lucasrmp-cb approved these changes

2024-08-14 01:34 UTC, merged