Removes unnecessary code and libs
Stand-With-Crypto/swc-web pull request #1254
Opened 2024-08-21 15:08 UTC by twistershark

## What changed? Why?

This PR removes dead code(with some exceptions like: unused ui components, intl and a few others), removes unnecessary exports and removes unused libs.

With this, we expect to improve bundle size, project organization and possibly improve hot reload timings because of this statement:  `The file you're editing might have other exports in addition to a React component.` in [Hot Reload Doc
](https://nextjs.org/docs/architecture/fast-refresh#limitations).

## Notes to reviewers

All of the analysis around these unnecessary files were done using this awesome lib: https://knip.dev/

## How has it been tested?

- [x] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-08-22 15:21 UTC, olavoparno submitted a review, later dismissed

2024-08-26 13:13 UTC, lucasrmp-cb requested changes

2024-08-26 13:13 UTC, lucasrmp-cb commented on src/components/ui/form.tsx
> -  useFormField,
This is supposed to be an abstracted internal lib, I think we should leave this so in case we need this hook in the future it's clear that it should come from here and not from react-hook-form

2024-08-26 13:49 UTC, twistershark commented on src/components/ui/form.tsx
> -  useFormField,
Updated!

2024-08-26 13:49 UTC, twistershark commented on src/utils/shared/sharedAnalytics.ts
>  }
Updated!

2024-08-26 14:01 UTC, lucasrmp-cb approved these changes

2024-08-26 14:27 UTC, merged