Voter guide page
Stand-With-Crypto/swc-web pull request #1316
Opened 2024-08-28 18:56 UTC by eduardopicolo-cb

closes 

fixes 

## What changed? Why?

![image](https://github.com/user-attachments/assets/02641701-e16a-4d1d-a37b-75eb91198db8)

![image](https://github.com/user-attachments/assets/08a9164e-9771-488e-94a4-b00829ba6421)

## PlanetScale deploy request

## Notes to reviewers

## How has it been tested?

- [x] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-09-09 13:37 UTC, lucasrmp-cb requested changes

2024-09-09 13:37 UTC, lucasrmp-cb commented on src/components/app/pageVoterGuide/keyRacesForm.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Not a big fan of using this for these kinds of cases. I usually recommend creating a ref of the dependency you don't want to trigger and using it inside the effect, that way you don't remove the check on all the other dependencies that should in fact be in the array.

Something like this should do the trick:
```typescriptreact
const createViewKeyRacesActionRef = React.useRef(createViewKeyRacesAction)
createViewKeyRacesActionRef.current = createViewKeyRacesAction

React.useEffect(() => {
  void createViewKeyRacesActionRef.current()
}, [])
```

2024-09-09 13:37 UTC, lucasrmp-cb commented on src/components/app/pageVoterGuide/voterJourneyStepCard.tsx
> +  }
We shouldn't use this pattern of rendering due to problems it can cause with component life cycle in some cases. Let's refactor this so this image is a separate component in the same file

2024-09-09 13:37 UTC, lucasrmp-cb commented on src/components/app/userActionFormVotingInformationResearched/constants.ts
> +}
Let's keep the pattern for enum naming, it should be pascal case and all the values in constant case.
```suggestion
export enum SectionsNames {
  LOADING = 'Loading',
  ADDRESS = 'Address',
  SUCCESS = 'Success',
}
```

2024-09-09 13:37 UTC, lucasrmp-cb commented on src/components/app/userActionFormVotingInformationResearched/constants.ts
> +}
Gonna add it to eslint

2024-09-09 13:37 UTC, lucasrmp-cb commented on src/components/app/userActionFormVotingInformationResearched/sections/address.tsx
> +export const Address = (props: AddressProps) => {
This should use the `function` to define
https://github.com/Stand-With-Crypto/swc-web/blob/645b0e8cf20a127293e1987a2514219615433169/docs/Coding%20Conventions.md#L27

2024-09-09 13:37 UTC, lucasrmp-cb commented on src/components/app/userActionFormVotingInformationResearched/sections/address.tsx
> +  const addressField = form.watch('address')
Let's use `useWatch` here

2024-09-09 13:37 UTC, lucasrmp-cb commented on src/components/app/userActionFormVotingInformationResearched/sections/address.tsx
> +            })
You are already toasting a generic message, and we can't guarantee `e.message` is a human readable message. Let's not show this message to the end user

2024-09-09 13:37 UTC, lucasrmp-cb commented on src/components/app/userActionFormVotingInformationResearched/sections/address.tsx
> +          Check your voting information
In other forms we usually show a `Loading...` message when we're submitting (not the prettiest, but effective), let's add it here too
```suggestion
          {form.formState.isSubmitting ? 'Loading...' : 'Check your voting information'}
```

2024-09-09 15:49 UTC, eduardopicolo-cb commented on src/actions/actionCreateUserActionVoterAttestation.ts
> +  const shouldBypassAuth = validatedInput.data.shouldBypassAuth
This is necessary to reduce friction for the voter guide. We need to allow unauthenticated users to complete the first step

2024-09-10 11:01 UTC, lucasrmp-cb approved these changes

2024-09-10 11:02 UTC, lucasrmp-cb commented on src/actions/actionCreateUserActionVoterAttestation.ts
> +  const shouldBypassAuth = validatedInput.data.shouldBypassAuth
Got this, I'm saying since there's a use case where this route can be called without authentication we can remove it all together and only authenticate on the client when we want to have it

2024-09-10 12:53 UTC, twistershark commented on src/components/app/pageVoterGuide/keyRacesForm.tsx
> +export const KeyRacesForm = (props: KeyRacesFormProps) => {
nit pick: Based on our Coding Conventions this should be declared with the function keyword

2024-09-10 12:53 UTC, twistershark approved these changes

2024-09-10 14:26 UTC, merged