Prevents broken address from being processed on backfill repeatedly
Stand-With-Crypto/swc-web pull request #1338
Opened 2024-09-02 18:32 UTC by twistershark

closes #1234 

## What changed? Why?

This PR saves the district number as 'NOT_FOUND' to prevent addresses that are broken from being processed everyday in the backfill cron job.

## How has it been tested?

- [x] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-09-02 18:41 UTC, lucasrmp-cb submitted a review, later dismissed

2024-09-02 18:45 UTC, olavoparno approved these changes

2024-09-02 20:14 UTC, mhamendes requested changes

2024-09-02 20:14 UTC, mhamendes commented on src/inngest/functions/backfillCongressionalDistrictCronJob/index.ts
> +        )
Those responses are not enough, they don't include error 400 on the API. Those errors will probably return as `CIVIC_API_DOWN`, so we must also treat those errors inside the query to the api.

2024-09-04 15:39 UTC, mhamendes approved these changes

2024-09-04 16:32 UTC, merged