refactor: adjust script to run faster
Stand-With-Crypto/swc-web pull request #1356
Opened 2024-09-04 19:27 UTC by olavoparno

closes  https://github.com/Stand-With-Crypto/swc-internal/issues/181

fixes 

## What changed? Why?

## PlanetScale deploy request

## Notes to reviewers

## How has it been tested?

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-09-04 22:06 UTC, lucasrmp-cb requested changes

2024-09-04 22:06 UTC, lucasrmp-cb commented on src/inngest/functions/backfillReactivation/index.tsx
> +        )) as string[]
Lets remove this cast and set the return type of `sendBatchEmails`, you might need to do a casting on there

2024-09-04 22:06 UTC, lucasrmp-cb commented on src/utils/server/email/sendMail.ts
> +  return response[0].headers?.['x-message-id'] as string
Is this right? `response` is gonna be an array even when `isMultiple === false`?

2024-09-05 15:01 UTC, olavoparno commented on src/inngest/functions/backfillReactivation/index.tsx
> +        )) as string[]
I forgot to remove from there. sendMail is type aware thus inferring it.

2024-09-05 15:07 UTC, olavoparno commented on src/utils/server/email/sendMail.ts
> +  return response[0].headers?.['x-message-id'] as string
It is always an array, it was like this before:

```ts
const [response] = await SendGrid.send()
```

2024-09-05 15:09 UTC, olavoparno commented on src/inngest/functions/backfillReactivation/index.tsx
> +      messageId: emailResults.find(result => result.userId === userId)!.messageId,
right now nothing happens. I will add it into inngest's response

2024-09-05 20:04 UTC, LucasdRossi commented on src/utils/server/email/sendMail.ts
> +        (currentResponse as [ClientResponse])[0].headers?.['x-message-id'] as string,
do we actually need this as string in both returns?

2024-09-05 20:05 UTC, LucasdRossi commented on src/utils/server/email/sendMail.ts
> +  const response = await SendGrid.send(parsedPayload as MailDataRequired, isMultiple)
do we need this `as MailDataRequired`?

2024-09-05 20:06 UTC, LucasdRossi commented on src/inngest/functions/backfillReactivation/index.tsx
> +      .map(action => action.actionType as EmailActiveActions)
do we need this `as EmailActiveActions`?

2024-09-05 20:07 UTC, olavoparno commented on src/utils/server/email/sendMail.ts
> +  const response = await SendGrid.send(parsedPayload as MailDataRequired, isMultiple)
no, we actually don't. thanks for spotting it

2024-09-05 20:08 UTC, olavoparno commented on src/utils/server/email/sendMail.ts
> +        (currentResponse as [ClientResponse])[0].headers?.['x-message-id'] as string,
not really, it was old code before the overload interfaces. thanks man

2024-09-05 20:09 UTC, LucasdRossi commented on src/inngest/functions/backfillReactivation/index.tsx
> +      errors: any[]
If we don't know the type of the error and we're not using it we should type it as **unknown**, so I would use `unknown[]` here instead of `any[]`

2024-09-05 20:09 UTC, LucasdRossi commented on src/inngest/functions/backfillReactivation/index.tsx
> +  const errors: any[] = []
same as the above comment

2024-09-05 20:10 UTC, olavoparno commented on src/inngest/functions/backfillReactivation/index.tsx
> +      .map(action => action.actionType as EmailActiveActions)
thanks

2024-09-05 20:13 UTC, LucasdRossi submitted a review, later dismissed

2024-09-06 12:38 UTC, twistershark approved these changes

2024-09-06 14:40 UTC, lucasrmp-cb approved these changes

2024-09-06 14:41 UTC, merged