New grid CTAs
Stand-With-Crypto/swc-web pull request #1418
Opened 2024-09-16 13:01 UTC by twistershark

closes  #928 

## What changed? Why?

This PR changes how we display the actions CTAs on home and profile page

## How has it been tested?

- [x] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-09-17 21:09 UTC, olavoparno commented on src/components/app/userActionGridCTAs/userActionGridCTAsForSuccessScreen.tsx
> +    <CampaignsDialog
is this order on purpose?

2024-09-17 21:09 UTC, olavoparno commented on src/components/app/userActionGridCTAs/userActionGridCTAsForSuccessScreen.tsx
> +  const isReadOnly =
could this be simplified a little bit?

2024-09-17 21:09 UTC, olavoparno commented on src/utils/shared/getUserActionsProgress.ts
> +  const performeduserActionObj = performedUserActionTypes.reduce(
adjust camelCase variable `performedUserActionObj`

2024-09-17 21:11 UTC, olavoparno commented on src/utils/shared/getUserActionsProgress.ts
> +  const allCampaignsCombined: Array<UserActionGridCTACampaign> = flatMap(
can the filtering for excludedCampaigns be done in the second argument of flatMap?

2024-09-17 21:14 UTC, olavoparno commented on src/components/app/userActionGridCTAs/userActionGridCTAsForSuccessScreen.tsx
> +        const completedCampaigns = cta.campaigns.reduce((acc, campaign) => {
to all campaigns iterations, is there a possibility of having it null or undefined? I mean, there's always at least 1, even if default, right?

2024-09-17 21:14 UTC, olavoparno commented on src/components/app/userActionGridCTAs/userActionGridCTAsForSuccessScreen.tsx
> +        const key = `${campaign.actionType}-${campaign.campaignName}`
is this only for the sake of counting? if so better use forEach

2024-09-17 21:15 UTC, olavoparno commented on src/components/app/userActionGridCTAs/userActionGridCTAsForSuccessScreen.tsx
> +    ctas.map(cta => {
same thing here as above

2024-09-17 21:17 UTC, olavoparno commented on src/components/app/userActionGridCTAs/userActionCard.tsx
> +      {...props}
same thing here for the order of props and spreading

2024-09-17 21:40 UTC, mhamendes requested changes

2024-09-17 21:40 UTC, mhamendes commented on src/components/app/userActionGridCTAs/userActionGridCTAsForSuccessScreen.tsx
> +  }, [ctas, performeduserActionObj])
This is really complex and looks like will be really hard to maintain. Wouldn't this be enough?


```js
  type CTAType = {
    title: string
    description: string
    mobileCTADescription?: string
    campaignsModalDescription: string
    link?: (args: { children: React.ReactNode }) => React.ReactNode
    image: string
    campaigns: Array<UserActionGridCTACampaign>
  }

  const orderedCTAs = useMemo(() => {
    const incompleteCTAs: CTAType[] = [];
    const completeCTAs: CTAType[] = [];

    ctas.forEach((cta) => {
      const numberOfCampaigns = cta.campaigns.length;

      const completedActions = ctas.campaigns.map((campaign) => {
        const key = `${campaign.actionType}-${campaign.campaignName}`
        if (!performeduserActionObj[key]) return

        return key;
      }).filter(Boolean)

      if (numberOfCampaigns <= completedActions.length) return completeCTAS.push(cta)

      return incompleteCTAs.push(cta);
    })

    return uniqBy([...incompleteActions, ...completeActions], cta => `${cta.title}-${cta.description}`)
  }, [ctas, performeduserActionObj])
```

2024-09-18 12:40 UTC, twistershark commented on src/components/app/userActionGridCTAs/userActionGridCTAsForSuccessScreen.tsx
> +    <CampaignsDialog
Yes... If the CTA has the link prop, we use that are the top priority. 

If the CTA has only one campaign, we call the campaign wrapper to prevent showing that modal showing all campaigns as it was happening on the bug bash for the login CTA.

If none of the above, it means that we have multiple campaigns and the CTA is not a link, so open the `CampaignsDialog` to show all campaigns

2024-09-18 12:42 UTC, twistershark commented on src/components/app/userActionGridCTAs/userActionGridCTAsForSuccessScreen.tsx
> +  const isReadOnly =
Updated. Check if it makes more sense now or if you have any other suggestion for it

2024-09-18 12:51 UTC, twistershark commented on src/utils/shared/getUserActionsProgress.ts
> +  const allCampaignsCombined: Array<UserActionGridCTACampaign> = flatMap(
Yes! Updated

2024-09-18 13:00 UTC, twistershark commented on src/components/app/userActionGridCTAs/userActionCard.tsx
> +      {...props}
If I spread the props after `description` and `performedUserActions`, TS is complaining that I'm repeating the same property multiple times. By using spread first, I can make sure that these two specific props will have that specified value

2024-09-18 13:04 UTC, twistershark commented on src/components/app/userActionGridCTAs/userActionGridCTAsForSuccessScreen.tsx
> +        const completedCampaigns = cta.campaigns.reduce((acc, campaign) => {
Yeah... We could wrongly set a CTA's campaigns as an empty array, but that would break the app and we would notice that the page would not load. Other than that, we can't set campaigns prop as undefined or null as it is required

2024-09-18 13:54 UTC, twistershark commented on src/components/app/userActionGridCTAs/userActionGridCTAsForSuccessScreen.tsx
> +  }, [ctas, performeduserActionObj])
Applied

2024-09-18 14:13 UTC, olavoparno commented on src/components/app/userActionGridCTAs/components/successScreenActionCard.tsx
> +  link: _link,
what's this for? link: _link

2024-09-18 14:26 UTC, olavoparno approved these changes

2024-09-18 17:31 UTC, mhamendes approved these changes

2024-09-20 17:08 UTC, merged