feat: child logger
Stand-With-Crypto/swc-web pull request #1432
Opened 2024-09-18 18:27 UTC by LucasdRossi

closes 

fixes 

## What changed? Why?

## PlanetScale deploy request

## Notes to reviewers

## How has it been tested?

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-09-18 18:58 UTC, olavoparno approved these changes

2024-09-18 19:03 UTC, lucasrmp-cb requested changes

2024-09-18 19:03 UTC, lucasrmp-cb commented on src/inngest/functions/setPrimaryCryptoAddressOfUser/logic.ts
> +  logger?: Logger,
Same here, if the idea is make `setPrimaryCryptoAddressOfUser` resilient we should just default this value to the return of `getLogger`
```suggestion
  logger: Logger = getLogger('setPrimaryCryptoAddressOfUser'),
```

2024-09-18 19:03 UTC, lucasrmp-cb commented on src/inngest/functions/sms/utils/enqueueMessages.ts
> +  logger?: Logger,
Same here, and let's merge `logger` and `attempt` in a `options` object, the API is easier to read that way

2024-09-18 19:29 UTC, LucasdRossi commented on src/inngest/functions/backfillCongressionalDistrictCronJob/index.ts
> +  logger?: Logger,
I thought about not linking the logic of the functions to a specific type in Inngest. There are some functions that separate the logic from the initialization and execution of Inngest:
[src/inngest/functions/backfillNFT
](https://github.com/Stand-With-Crypto/swc-web/tree/main/src/inngest/functions/backfillNFT)
[src/inngest/functions/cleanupPostalCodes ](https://github.com/Stand-With-Crypto/swc-web/tree/main/src/inngest/functions/cleanupPostalCodes)

2024-09-18 20:34 UTC, olavoparno submitted a review, later dismissed

2024-09-19 15:01 UTC, lucasrmp-cb commented on src/inngest/functions/backfillCongressionalDistrictCronJob/index.ts
> +  logger?: Logger,
You have a few options to suppress or even test console calls in jest, I think we can go towards something like this instead.
![image](https://github.com/user-attachments/assets/b7b9fcbf-dc52-4e86-b197-00a1b357d527)
Maybe we wanna mock logs based on and env or something like that. It serves as a test debug sometimes, I dont think we should change implementation thinking of tests but the other way around

2024-09-19 15:03 UTC, lucasrmp-cb commented on src/inngest/functions/backfillCongressionalDistrictCronJob/index.ts
> +  logger?: Logger,
And about not creating inngest dependencies. I get that and agree to some extend, but I'm ok with creating inngest dependencies inside the `inngest` folder

2024-09-19 15:07 UTC, lucasrmp-cb requested changes

2024-09-19 15:07 UTC, lucasrmp-cb commented on src/inngest/functions/cleanupPostalCodes/logic.ts
> +export async function cleanPostalCodes(persist: boolean, logger = defaultLogger) {
its still a np of mine (and you don't need to change it), but I don't like the signature call of `cleanPostalCodes(true, logger)`, I'd much prefer `cleanPostalCodes({ persist: true, logger })`, this way I know what `true` means

2024-09-19 15:07 UTC, lucasrmp-cb commented on src/inngest/functions/setPrimaryCryptoAddressOfUser/logic.ts
> +    logger.info('Dry run, exiting')
I know this is not your task, but I think we're missing a return here. Big problem so if you can check and fix

2024-09-19 15:30 UTC, olavoparno approved these changes

2024-09-19 16:17 UTC, lucasrmp-cb approved these changes

2024-09-19 16:34 UTC, merged