feat: add voting day user action
Stand-With-Crypto/swc-web pull request #1515
Opened 2024-10-17 15:40 UTC by olavoparno

closes  https://github.com/Stand-With-Crypto/swc-web/issues/1462

fixes 

## What changed? Why?

Added action to give users a NFT of the voting day

![image](https://github.com/user-attachments/assets/ec267f08-d89d-4dbb-8125-7c4d74599930)
![image](https://github.com/user-attachments/assets/c2792037-b0d1-49f6-81f5-5b55f67b9b7d)
![image](https://github.com/user-attachments/assets/49d6847a-8364-4c20-b0c6-f5c914bb9bc5)

![image](https://github.com/user-attachments/assets/a402216d-ecdd-4d2e-9be2-b1ac283c9fc3)

## PlanetScale deploy request

## Notes to reviewers

## How has it been tested?

- [X] Locally
- [x] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-10-22 13:53 UTC, lucasrmp-cb requested changes
Tests are failing, and can we also add a description to this PR, some screenshots explaining stuff that changed from figma, etc

2024-10-22 13:56 UTC, twistershark commented on src/actions/actionCreateUserActionVotingDay.ts
> +          usaState: userAddress?.address?.administrativeAreaLevel1 ?? null,
I'm not completely sure on this, but could this create any problem with users from DC?

2024-10-22 13:58 UTC, twistershark commented
@olavoparno You need to ask Travis to add the new NFT address env to github to fix the tests

2024-10-22 14:00 UTC, olavoparno commented
> @olavoparno You need to ask Travis to add the new NFT address env to github to fix the tests

I've asked already but the error was because I forgot to add the env in the cypress.yml file. Thanks man.

2024-10-22 14:01 UTC, olavoparno commented
> @olavoparno Are we going to add the "I voted" icon to the actions map on homepage? I think that it will be very important as this action will have a lot of visibility on election day

Excellent question. Lemme raise it up on the channel!

2024-10-22 14:05 UTC, twistershark commented
@olavoparno Another question:

I saw somewhere that people can vote before election day(not sure how it works), but if this is the case, are we going to show this new action as soon as this PR is shipped to prod or are we going to hide it until election day?

Also, we current show a grid of 3 actions, but it would be weird with this 4th one. If I'm not mistaken, I remember that I asked Mariano about this before and we said that we should change it to be 4 columns. I don't think that I saw this change in this PR and checking the preview env, I saw that we didn't change it. Can you check with him to confirm this?

2024-10-22 14:08 UTC, twistershark commented on src/components/app/userActionRowCTA/constants.tsx
> +  [UserActionType.VOTING_DAY]: {
Just a comment: You should not need to update this file anymore. I didn't remove the old row CTAs code so that we could easily revert the grid change it necessary. You prob added it here because typescript complained about it, but I'll create a task to remove these codes after election

2024-10-22 14:09 UTC, twistershark commented on src/components/app/userActionVotingDay/sections/didYouVote.tsx
> +    <>
Do you really need this fragment here?

2024-10-22 14:12 UTC, twistershark reviewed
.

2024-10-30 14:03 UTC, olavoparno commented
added into #1540 feat/live-results-new

2024-11-01 19:10 UTC, twistershark commented on src/components/app/userActionFormSuccessScreen/UserActionFormSuccessScreenFeedback.tsx
> +    ? props.description // Temporary description until 2024 election is over.
I believe we should establish a system to remind us to remove TODOs by their respective deadlines. Do you have any suggestions on how we might approach this?

One idea is to use a "TODO:" prefix, which could make it easier to locate these items in the future.

Additionally, we could create a document with GitHub permalinks for these scenarios, allowing us to reference them easily when removing a feature.

Just sharing some thoughts — this isn’t a blocker for merging.

2024-11-01 19:14 UTC, twistershark approved these changes

2024-11-01 20:21 UTC, lucasrmp-cb approved these changes

2024-11-01 20:27 UTC, merged