Feat/live results new
Stand-With-Crypto/swc-web pull request #1540
Opened 2024-10-29 20:07 UTC by olavoparno

closes  https://github.com/Stand-With-Crypto/swc-web/issues/1461

fixes 

## What changed? Why?

## PlanetScale deploy request

## Notes to reviewers

## How has it been tested?

- [X] Locally
- [X] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-11-01 22:19 UTC, travisbloom-cb commented on prisma/schema.prisma
> +model UserActionVotingDay {
can we update this PR so we dont include voting day diffs

2024-11-02 21:39 UTC, mhamendes commented on src/components/app/pageLocationKeyRaces/locationStateSpecific/index.tsx
> -  }, [stateCode])
This being removed is correct?

2024-11-02 21:39 UTC, mhamendes commented on src/components/app/pageLocationKeyRaces/locationStateSpecific/index.tsx
>  'use client'
This is a HUGE component with a lot of different rendering logics inside it, we could split this into multiple components to make it more maintainable.

2024-11-02 21:39 UTC, mhamendes commented on src/components/app/pageLocationKeyRaces/locationUnitedStates/index.tsx
> -
Was this also correctly removed?

2024-11-02 21:39 UTC, mhamendes commented on src/components/app/pageLocationKeyRaces/locationUnitedStatesLiveResults/index.tsx
> +            )}
We should probably memoize this, the logic is too complex to be added directly to component rendering.

2024-11-02 21:39 UTC, mhamendes commented on src/components/app/pageLocationKeyRaces/locationUnitedStatesLiveResults/keyRaceLiveResult.tsx
> +  }
This does not need to be memoized. This should do the trick.

```suggestion
  if (raceData?.candidatesWithVotes.length === 1) {
    return null
  }
```

2024-11-02 21:39 UTC, mhamendes commented on src/components/app/pageLocationKeyRaces/locationUnitedStatesLiveResults/useCandidateSelection.ts
> +    }
Nit: This nested ternary is definitely a code smell, we should avoid doing this.

2024-11-02 21:39 UTC, mhamendes commented on src/components/app/pageLocationKeyRaces/locationUnitedStatesLiveResults/presidentialRaceResult.tsx
> +}
We have a very simmilar function inside `src/components/app/pageLocationKeyRaces/locationUnitedStatesLiveResults/utils.ts`, can't we use it?

2024-11-02 21:39 UTC, mhamendes commented on src/components/app/pageLocationKeyRaces/locationUnitedStatesLiveResults/utils.ts
> +}
This function is more complex than it needs to be, you can make it more readable dividing the logic when its array from when it's not and working with early returns.

```suggestion
export const getRaceStatus = (
  raceData: RacesVotingDataResponse | RacesVotingDataResponse[] | null | undefined,
): RaceStatus => {
  if (!raceData) return 'unknown'

  const now = new Date()

  if (Array.isArray(raceData)) {
    if (raceData.length === 0) return 'unknown'
    if (raceData.every(race => race.hasCalledCandidate || race.advanceCandidates)) return 'called'
    if (raceData.some(race => +race.totalVotes > 0)) return 'live'

    const raceDate = new Date(raceData?.[0].raceDate || '2024-11-05')
    if (isBefore(startOfDay(now), startOfDay(raceDate))) return 'not-started'
    return 'live'
  }

  if (raceData.hasCalledCandidate) return 'called'
  if (raceData.advanceCandidates) return 'runoff'
  if (+raceData.totalVotes > 0) return 'live'

  const raceDate = new Date(raceData?.raceDate || '2024-11-05')
  if (isBefore(startOfDay(now), startOfDay(raceDate))) return 'not-started'
  return 'live'
}
```

2024-11-02 21:39 UTC, mhamendes commented on src/data/aggregations/decisionDesk/getAllCongressData.ts
> +  )
Are you rewriting the acc `office` and `year` for every entry and in the end getting only one `office` and `year`? If that is the case would be easier to flatmap the `candidatesWithVote`  and map through everything to get the `candidatesWithVote` instead.

Something like this maybe? Did not test it, so may need some changes.
```suggestion
const reduceCongressData = (congressData: RacesVotingDataResponse[]) => {
    const candidatesWithVoteFlatMap = congressData.flatMap(currentData => currentData.candidatesWithVotes);

    return {
      office: congressData[0].office,
      year: congressData[0].year,
      candidatesWithVotes: candidatesWithVoteFlatMap.map(currentCandidate => {
        const candidateVotes = candidatesWithVoteFlatMap.filter(candidate => candidate.id === currentCandidate.id)
        const totalVotes = candidateVotes.reduce((acc, current) => acc + current.votes, 0)

        return {
          ...currentCandidate,
          votes: totalVotes,
      }}),
    }
  }
```

2024-11-02 21:39 UTC, mhamendes commented on src/data/pageSpecific/getKeyRacesPageData.ts
> +    throw new Error('No ddhq presidential race data')
If we are throwing here, no need to throw on the page render as well.

2024-11-02 21:39 UTC, mhamendes commented on src/inngest/functions/decisionDesk/fetchPresidentialRacesData.ts
> +      }
Looks like we are getting a looooot of data, do we have enough memory in each inngest call to save everything?

2024-11-02 21:39 UTC, mhamendes commented on src/utils/server/decisionDesk/getElectedCandidates.ts
> +        // }
Should this be kept commented out?

2024-11-02 21:39 UTC, mhamendes commented on src/utils/server/decisionDesk/getElectionStatus.ts
> +      console.error(`Error fetching ${currentStateKey} state`, (error as Error).message)
Should we send this error to Sentry and log it correctly using our logger function?

2024-11-02 22:07 UTC, lucasrmp-cb requested changes

2024-11-02 22:07 UTC, lucasrmp-cb commented on src/inngest/functions/decisionDesk/fetchPresidentialRacesData.ts
> +        fs.writeFileSync(
Are we writing to a file inside the vercel serverless function location? Where does this goes to?

2024-11-02 22:07 UTC, lucasrmp-cb commented on src/inngest/functions/decisionDesk/fetchPresidentialRacesData.ts
> +          fs.writeFileSync(
Same here

2024-11-02 22:07 UTC, lucasrmp-cb commented on src/inngest/functions/decisionDesk/fetchPresidentialRacesData.ts
> +          fs.writeFileSync(
Same here

2024-11-02 22:07 UTC, lucasrmp-cb commented on src/inngest/functions/decisionDesk/fetchPresidentialRacesData.ts
> +        fs.writeFileSync(
I think I got the idea here, and we should be using blob storage and not use the file system as a database here. Why do we need this and why this solution instead of a proper storage?

2024-11-04 12:25 UTC, olavoparno commented on src/inngest/functions/decisionDesk/fetchPresidentialRacesData.ts
> +          fs.writeFileSync(
this is only meant to be used locally, to generate mock files, this persistFile variable is set as false but I should add also a control with the environment, thanks for noticing.

2024-11-04 12:25 UTC, olavoparno commented on src/inngest/functions/decisionDesk/fetchPresidentialRacesData.ts
> +          fs.writeFileSync(
this is only meant to be used locally, to generate mock files, this persistFile variable is set as false but I should add also a control with the environment, thanks for noticing.

2024-11-04 12:25 UTC, olavoparno commented on src/inngest/functions/decisionDesk/fetchPresidentialRacesData.ts
> +        fs.writeFileSync(
this is only meant to be used locally, to generate mock files, this persistFile variable is set as false but I should add also a control with the environment, thanks for noticing.

2024-11-04 12:27 UTC, olavoparno commented on src/data/aggregations/decisionDesk/getAllRacesData.ts
> +  const pageIteration = Array.from({ length: total_pages - 1 }, (_, i) => (i + 2).toString())
this is used to fetch all data from decisionDesk and yeah this must be improved indeed but right now it's the only way we found to fetch their paginated data :(

2024-11-04 12:44 UTC, olavoparno commented on sentry.client.config.ts
> +const COMMON_TRANSACTION_NAMES_TO_GROUP = ['node_modules/@thirdweb-dev', 'maps/api/js', '/races']
this was a mistake, removing and thanks for spotting

2024-11-04 12:45 UTC, olavoparno commented on src/utils/shared/urls/index.ts
> +    locationCongressSenate: () => `${localePrefix}/races/congress/senate`,
We have separate pages for each

2024-11-04 12:51 UTC, olavoparno commented on src/app/api/public/decision-desk/usa/state/[state]/district/[district]/route.ts
> +        status: 400,
yup changing it thanks

2024-11-04 12:52 UTC, olavoparno commented on src/app/api/public/decision-desk/usa/state/[state]/district/[district]/route.ts
> +      { status: 400 },
yup changing it thanks

2024-11-04 12:57 UTC, olavoparno commented on src/app/[locale]/races/congress/house/page.tsx
> +  }
adjusting, thanks for noticing

2024-11-04 12:58 UTC, olavoparno commented on src/app/[locale]/races/congress/senate/page.tsx
> +  }
adjusting, thanks for noticing

2024-11-04 13:15 UTC, olavoparno commented on src/inngest/functions/decisionDesk/fetchPresidentialRacesData.ts
> +      }
we do but I should've been more clear on it. this only runs locally to generate mock files, so we don't save anything on the cloud other than redis' registries.

2024-11-04 13:33 UTC, olavoparno commented on src/data/aggregations/decisionDesk/getAllCongressData.ts
> +  )
you're definitely right, man, commiting your change thanks

2024-11-04 13:49 UTC, twistershark commented on src/components/app/pageLocationKeyRaces/locationRaceSpecific/organizeRaceSpecificPeople.ts
> +      : DTSI_PersonRoleCategory.PRESIDENT
+1

2024-11-04 14:05 UTC, twistershark commented on src/inngest/functions/decisionDesk/fetchPresidentialRacesData.ts
> +        fs.writeFileSync(
@olavoparno wouldn't it be better to separate the logic in this function outside of inngest and then create a script for local file generation and call the functions inside this inngest cron?

2024-11-04 14:07 UTC, twistershark commented on src/inngest/functions/decisionDesk/fetchPresidentialRacesData.ts
> +const persistFile = NEXT_PUBLIC_ENVIRONMENT === 'local' && false
I think that this condition will always be false. Is that the real objective here?

2024-11-04 14:13 UTC, olavoparno commented on src/inngest/functions/decisionDesk/fetchPresidentialRacesData.ts
> +const persistFile = NEXT_PUBLIC_ENVIRONMENT === 'local' && false
this is only meant for local use indeed to create mock files

2024-11-04 14:41 UTC, twistershark commented on src/components/app/pageLocationKeyRaces/locationUnitedStatesLiveResults/presidentialRaceResult.tsx
> +      {/* {percentage ? <span className="text-center font-bold">{percentage.toFixed(2)}%</span> : null} */}
Do we still need this code?

2024-11-04 14:47 UTC, twistershark commented on src/hooks/useApiDecisionDeskStateData.ts
> +    !hasHydrated
np: nested ternaries

2024-11-04 14:48 UTC, twistershark commented on src/hooks/useApiDecisionDeskStateData.ts
> +      refreshInterval: 30 * 1000,
np: 
```suggestion
      refreshInterval: 30 * 1000, // 30 SECONDS
```

2024-11-04 16:14 UTC, eduardopicolo-cb commented on src/app/[locale]/races/congress/house/page.tsx
> +  )
The error is thrown server-side, we want that to ensure every race page is pre-generated successfully. Users will not see the error page because the app won't be built in case of errors

2024-11-04 16:17 UTC, eduardopicolo-cb commented on src/app/[locale]/races/presidential/page.tsx
> +    presidentialRaceLiveResult = await getDecisionDataFromRedis<
This function is also used in api routes, so it is better to throw specific errors in each page for better Sentry tracking

2024-11-04 16:19 UTC, eduardopicolo-cb commented on src/app/[locale]/races/presidential/page.tsx
> +  )
Yes, to throw here is the expected behavior to block builds. Users wont see the error page

2024-11-04 16:45 UTC, eduardopicolo-cb commented on src/components/app/pageLocationKeyRaces/locationUnitedStatesLiveResults/presidentialRaceResult.tsx
> +}
its similiar but the presidential one has a very different data object

2024-11-04 16:51 UTC, eduardopicolo-cb commented on src/components/app/pageLocationKeyRaces/locationUnitedStates/index.tsx
> -
yes

2024-11-04 17:03 UTC, eduardopicolo-cb commented on src/app/[locale]/races/state/[stateCode]/district/[district]/page.tsx
> +    throw new Error(`No ddhq data for LocationDistrictSpecificPage: ${JSON.stringify(params)}`)
After a build is successfully generated we should always have a stale version  to fallback to, and then have Sentry issues if revalidation fails

2024-11-04 18:01 UTC, mhamendes commented on src/app/[locale]/races/presidential/page.tsx
> +  )
Got it, we are building all pages during the build.

2024-11-04 18:03 UTC, mhamendes commented on src/app/[locale]/races/state/[stateCode]/page.tsx
> +    throw new Error(
Answered

2024-11-04 18:05 UTC, mhamendes commented on src/app/[locale]/races/presidential/page.tsx
> +    presidentialRaceLiveResult = await getDecisionDataFromRedis<
Sentry already tracks which page threw that error, it seems redundant to throw this error twice and capture the error twice on Sentry (both inside the function and on the page).

2024-11-04 21:22 UTC, mhamendes submitted a review, later dismissed
LGTM

2024-11-04 21:22 UTC, travisbloom-cb approved these changes

2024-11-04 21:25 UTC, lucasrmp-cb reviewed
SHIP IT 🚀

2024-11-04 21:25 UTC, lucasrmp-cb submitted a review, later dismissed

2024-11-04 21:31 UTC, merged