style: adjust politician table and other stuff
Stand-With-Crypto/swc-web pull request #1623
Opened 2024-11-26 00:20 UTC by olavoparno

closes  https://github.com/Stand-With-Crypto/swc-web/issues/815

fixes 

## What changed? Why?

## PlanetScale deploy request

## Notes to reviewers

## How has it been tested?

- [X] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-11-26 13:03 UTC, LucasdRossi commented on src/components/app/dtsiClientPersonDataTable/dataTable.tsx
> +    const currentParams = new URLSearchParams(searchParams?.toString() ?? '')
Do you really need to instantiate URLSearchParams again here? Can't you use `params` from line 105?

2024-11-26 13:05 UTC, LucasdRossi commented on src/components/app/dtsiClientPersonDataTable/dataTable.tsx
> +  }, [])
I would move this to a separate hook: `useResize`

2024-11-26 13:07 UTC, LucasdRossi commented on src/components/app/dtsiClientPersonDataTable/dataTable.tsx
> +                {table.getRowModel().rows?.length ? (
Move `table.getRowModel()` to a variable outside the rendering logic

2024-11-26 13:09 UTC, LucasdRossi commented on src/components/app/dtsiClientPersonDataTable/dataTable.tsx
> +                      }}
Move this to a function outside the render logic

2024-11-26 13:12 UTC, lucasrmp-cb commented
This closes more than one issue if I'm not mistaken, right? Let's add the `closes` keyword for all of them

2024-11-26 13:32 UTC, lucasrmp-cb requested changes

2024-11-26 13:32 UTC, lucasrmp-cb commented on src/components/app/dtsiClientPersonDataTable/dataTable.tsx
> +  }, [])
For the resize logic we have this in the `useResizeObserver` hook, all you need yo do is pass it with the document ref and it should give you width and height of the bounding client rect.

And also, why would the width change on scroll?

2024-11-26 13:32 UTC, lucasrmp-cb commented on src/components/app/dtsiClientPersonDataTable/dataTable.tsx
> +  }, [columnFilters, globalFilter, pathname, router, searchParams, sorting])
```
https://swc-web-git-refactor-style-n-other-stuff-coinbase-vercel.vercel.app/politicians?filters=%5B%7B%22id%22%3A%22swcStanceScore%22%2C%22value%22%3A%22All%22%7D%2C%7B%22id%22%3A%22primaryRole%22%2C%22value%22%3A%22All%22%7D%2C%7B%22id%22%3A%22politicalAffiliationCategory%22%2C%22value%22%3A%22All%22%7D%2C%7B%22id%22%3A%22state%22%2C%22value%22%3A%22All%22%7D%5D&sorting=%5B%5D&globalFilter=
```

This is the url we're creating when opening the page when the only thing we're trying to do is persist 5 states in search params. I understand that the way the data table works is different than just states but why can't we create a controled state and add a persistence layer on top of it to only have the 5 query params instead of a bunch of unreadable text on the url?

The way I'd think about this issue would be to first make sure we have a controlled state of the filters and sorting (this you already have here), and then create a `useSearchParamsState` that would be the persistence layer between the query params and the state (explanation below)

The hook would receive a key an a default value as arguments, have the exact same return type as `useState` and work like this:
- It would have a setState in which it would check if the search params with that `key` is set and if so use it as default value and fallback to the one provided by the call (you can do this by passing a function as an argument to `useState`)
- It would wrap the `setState` function where it will set both the state from the `useState` call and also the `key` in the search params (without needing a reload since the filter value would be up to date)

We can pair on this if you like

2024-11-26 13:33 UTC, olavoparno commented on src/components/app/dtsiClientPersonDataTable/dataTable.tsx
> +  }, [])
Even though this handling two different events, I'm abstracting this to a separate hook. Thanks man

2024-11-26 13:33 UTC, olavoparno commented on src/components/app/dtsiClientPersonDataTable/dataTable.tsx
> +                      }}
Thanks man

2024-11-26 14:26 UTC, olavoparno commented on src/components/app/dtsiClientPersonDataTable/dataTable.tsx
> +  }, [])
It has to be recalculated on scroll to get the correct sum of header widths because it loses its style after changing the position to `fixed` and that's why I can't use the useResizeObserver. The header is virtually recreated because of this

2024-11-26 19:33 UTC, olavoparno commented on src/components/app/dtsiClientPersonDataTable/dataTable.tsx
> +  }, [columnFilters, globalFilter, pathname, router, searchParams, sorting])
thanks for the pairing man

2024-11-26 19:56 UTC, lucasrmp-cb requested changes

2024-11-26 19:56 UTC, lucasrmp-cb commented on src/hooks/useQueryParamState.ts
> +      setInternalState(valueToSet)
This is not necessary if you are only setting the internal state, just return `setInternalState` from the hook and it will work the same

2024-11-26 19:56 UTC, lucasrmp-cb commented on src/components/app/dtsiClientPersonDataTable/useTableFilters.ts
> +  const [searchValue, setSearchValue] = useSearchParamState('global')
Can we change the key here to something like `search`/`q`/`query`? It's a common pattern

2024-11-26 19:56 UTC, lucasrmp-cb commented on src/components/app/dtsiClientPersonDataTable/useTableFilters.ts
> +  const [searchValue, setSearchValue] = useSearchParamState('global')
We should have default values on this as an empty string, no?

2024-11-26 19:56 UTC, lucasrmp-cb commented on src/components/app/dtsiClientPersonDataTable/useTableFilters.ts
> +  const [sortValue, setSortValue] = useSearchParamState('sorting')
Same here

2024-11-26 20:19 UTC, LucasdRossi commented on src/components/app/dtsiClientPersonDataTable/dataTable.tsx
> +  const [headerWidths, setHeaderWidths] = useState<number[]>([])
It's a good idea to keep all your useState calls together at the top of the function. I also like to group hooks by type, like putting all the useEffect and useMemo calls together. That way, it's easy to see all the states, memoized variables, and effects in one spot.

2024-11-27 19:43 UTC, olavoparno commented on src/components/app/dtsiClientPersonDataTable/dataTable.tsx
> +  }, [])
no longer on the PR

2024-11-27 19:43 UTC, olavoparno commented on src/hooks/useQueryParamState.ts
> +      setInternalState(valueToSet)
thanks

2024-11-27 19:43 UTC, olavoparno commented on src/components/app/dtsiClientPersonDataTable/useTableFilters.ts
> +  const [searchValue, setSearchValue] = useSearchParamState('global')
thanks

2024-11-27 19:44 UTC, olavoparno commented on src/components/app/dtsiClientPersonDataTable/dataTable.tsx
> +  const [headerWidths, setHeaderWidths] = useState<number[]>([])
thanks

2024-12-03 17:04 UTC, lucasrmp-cb requested changes

2024-12-03 17:04 UTC, lucasrmp-cb commented on src/hooks/useQueryParamState.ts
Let's change either the name of the file or the hook so they are the same

2024-12-03 18:45 UTC, lucasrmp-cb approved these changes

2024-12-03 18:49 UTC, merged