feat: creates synthetic tests clean up cron job
Stand-With-Crypto/swc-web pull request #1629
Opened 2024-11-29 16:21 UTC by twistershark

## What changed? Why?

To ensure we don't store unnecessary data, it's important to clean up any information generated by synthetic tests in the production environment, especially since we need to go through login and complete user actions during testing.

This PR deletes all user actions and email addresses related to synthetic test users.

## How has it been tested?

- [x] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-11-29 16:56 UTC, LucasdRossi commented on src/inngest/functions/datadog/cleanup/index.ts
> +      return prismaClient.user.findMany({
There is no need for this `async` and you also don't need to open the arrow function since you're just returning a Promise

```suggestion
    const users = await step.run('script.getSyntheticTestUsers', () => prismaClient.user.findMany({
```

2024-11-29 16:57 UTC, LucasdRossi commented on src/inngest/functions/datadog/cleanup/index.ts
> +    })
Same here, you don't need to open the arrow function

```suggestion
    await step.run('script.removeUserActions', () => Promise.all(userActionRemovalPromises))
```

2024-11-29 16:59 UTC, LucasdRossi commented on src/inngest/functions/datadog/cleanup/index.ts
> +    })
Same here

```suggestion
    await step.run('script.removeUserEmails', async () => Promise.all(userEmailRemovalPromises))
```

2024-11-29 17:00 UTC, LucasdRossi commented on src/inngest/functions/datadog/cleanup/index.ts
> +    })
Same here

```suggestion
    await step.run('script.updateUsers', () => Promise.all(usersToUpdatePromises))
```

2024-11-29 17:07 UTC, LucasdRossi submitted a review, later dismissed

2024-12-02 18:37 UTC, olavoparno approved these changes

2024-12-02 18:51 UTC, eduardopicolo-cb requested changes

2024-12-02 18:51 UTC, eduardopicolo-cb commented on src/inngest/functions/datadog/cleanup/index.ts
> +    const filteredUsers = uniqBy(users, user => user.id)
We could add a check `filteredUsers.length === 0` before attempting deletions/updates

2024-12-03 16:26 UTC, merged