Feat/sentry error boundary
Stand-With-Crypto/swc-web pull request #1650
Opened 2024-12-11 19:42 UTC by olavoparno

closes  https://github.com/Stand-With-Crypto/swc-internal/issues/302

fixes 

## What changed? Why?

- add more granularity in terms of errors on our application with error boundaries

## PlanetScale deploy request

## Notes to reviewers

## How has it been tested?

- [X] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-12-11 20:36 UTC, eduardopicolo-cb requested changes
We also need to add the boundary to the actions deeplinks

2024-12-11 20:46 UTC, eduardopicolo-cb commented
There is also a new zod plugin for sentry https://github.com/getsentry/sentry-javascript/pull/11144, this should allow for better grouping for validation related errors

And this integration that should add more error data from third-party errors https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/integrations/extraerrordata/

2024-12-11 20:56 UTC, olavoparno commented
> There is also a new zod plugin for sentry [getsentry/sentry-javascript#11144](https://github.com/getsentry/sentry-javascript/pull/11144), this should allow for better grouping for validation related errors
> 
> And this integration that should add more error data from third-party errors https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/integrations/extraerrordata/

we already have `Sentry.extraErrorDataIntegration()` in place

2024-12-12 17:25 UTC, lucasrmp-cb requested changes

2024-12-12 18:00 UTC, olavoparno commented on src/utils/web/errorBoundary/index.tsx
> +      fallback={fallback ?? ErrorFallbackComponent}
cool, you're right. removed it

2024-12-12 18:00 UTC, olavoparno commented on src/utils/web/errorBoundary/index.tsx
> +        scope.setLevel(severityLevel ?? 'warning')
thanks. adjusted it

2024-12-12 20:35 UTC, lucasrmp-cb approved these changes

2024-12-12 20:39 UTC, eduardopicolo-cb approved these changes

2024-12-12 20:39 UTC, merged