test: dynamic page rendering builder content
Stand-With-Crypto/swc-web pull request #1704
Opened 2024-12-30 18:45 UTC by LucasdRossi

closes 

fixes 

## What changed? Why?

## PlanetScale deploy request

## Notes to reviewers

## How has it been tested?

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2025-01-10 19:34 UTC, olavoparno commented on src/app/[locale]/layout.tsx
> +            <MaybeBuilderContent>
is this used to hide components if rendering a builder.io page?

2025-01-10 19:36 UTC, olavoparno commented on src/components/ui/button/button.builder.tsx
> +import { Builder, withChildren } from '@builder.io/react'
add "use client"

2025-01-10 19:57 UTC, olavoparno commented on src/utils/server/builder/models/page/content.ts
> +    return pathname.startsWith(this.routePrefix)
using `this` here is magic unless people really know the class it is extending

2025-01-10 20:03 UTC, olavoparno commented on src/utils/server/builder/serverCMS.ts
> +const NEXT_PUBLIC_BUILDER_IO_PUBLIC_KEY = requiredOutsideLocalEnv(
do we really need it to be publicly accessible? We should make this private

2025-01-10 20:05 UTC, olavoparno commented on src/utils/server/builder/serverCMS.ts
> +const NEXT_PUBLIC_BUILDER_IO_PUBLIC_KEY = requiredOutsideLocalEnv(
this could remain private, couldn't it? is there a need to expose it?

2025-01-13 14:05 UTC, LucasdRossi commented on src/utils/server/builder/serverCMS.ts
> +const NEXT_PUBLIC_BUILDER_IO_PUBLIC_KEY = requiredOutsideLocalEnv(
Yes, we need to use it to initialize builder on the client [here](https://github.com/Stand-With-Crypto/swc-web/blob/d46412909af3bd17e01695d81bb2810caa5d46b2/src/utils/web/builder/clientCMS.ts), so it needs to be public

2025-01-13 14:08 UTC, travisbloom-cb requested changes

2025-01-13 14:08 UTC, travisbloom-cb commented on src/app/[locale]/topLevelClientLogic.tsx
> +import '@/utils/web/builder/registerComponents'
we only want this imported on builder.io pages

2025-01-13 14:08 UTC, travisbloom-cb commented on src/components/app/builder.tsx
> +  if (!hasHydrated) {
Does this mean no builder.io pages will server side render? This seems like a pretty big issue/bug

2025-01-13 14:08 UTC, travisbloom-cb commented on src/components/app/builderPageLayout.tsx
> +      {details.hasNavbar && <Navbar locale={locale} />}
The better way of doing this is prob to have a Navbar and Footer builder component

2025-01-13 14:08 UTC, travisbloom-cb commented on src/components/ui/button/button.builder.tsx
> +const Button = dynamic(() => import('@/components/ui/button').then(mod => mod.Button))
Why are we making this a dynamic import?

2025-01-13 14:08 UTC, travisbloom-cb commented on src/utils/server/builder/models/data/events.ts
> +export async function getEvent(eventSlug: string, state: string) {
Why did we modify?

2025-01-13 14:08 UTC, travisbloom-cb commented on src/utils/server/builder/models/page/PageModel.ts
> +export abstract class PageModel {
We don't use class-based architecture anywhere else. Prob shouldnt start now

2025-01-13 14:08 UTC, travisbloom-cb commented on src/utils/server/builder/models/page/content.ts
> +class ContentPageModel extends PageModel {
see class comment

2025-01-13 14:08 UTC, travisbloom-cb commented on src/utils/server/builder/models/page/page.ts
> +class DefaultPageModel extends PageModel {
see class comment

2025-01-13 14:08 UTC, travisbloom-cb commented on src/utils/server/builder/models/page/page.ts
> +  public readonly pages = {
This architecture is problematic. We don't want to have to update the codebase everytime someone needs to ship a new page. Can you explain why we need this?

2025-01-13 14:08 UTC, travisbloom-cb commented on src/utils/server/builder/models/page/utils/isBuilderPage.ts
> +export function isBuilderPage(pathname: string | null) {
see comment above. This architecture is problematic. We don't want to have to update the codebase everytime someone needs to ship a new page. Can you explain why we need this?

2025-01-13 14:31 UTC, LucasdRossi commented on src/app/[locale]/content/[[...page]]/page.tsx
> +import { serverCMS } from '@/utils/server/builder/serverCMS'
I agree. Do you think we should keep it inside the `utils` folder or have a `builderio` folder directly inside `src`?

2025-01-13 17:11 UTC, LucasdRossi commented on src/utils/server/builder/models/data/events.ts
> +export async function getEvent(eventSlug: string, state: string) {
I didn't modify the function, just moved it to a new location and grouped all of the events data model fetching logic to the same file

2025-01-13 17:22 UTC, LucasdRossi commented on src/components/ui/button/button.builder.tsx
> +const Button = dynamic(() => import('@/components/ui/button').then(mod => mod.Button))
You're right, we should only use dynamic imports for non-critical components. I'll remove the dynamic import

2025-01-13 17:36 UTC, travisbloom-cb commented on src/app/[locale]/content/[[...page]]/page.tsx
> +import { serverCMS } from '@/utils/server/builder/serverCMS'
i think the folder structure is fine, was mainly commenting on the variable name

2025-01-13 17:36 UTC, travisbloom-cb commented on src/components/ui/button/button.builder.tsx
> +const Button = dynamic(() => import('@/components/ui/button').then(mod => mod.Button))
I dont think we'd want any dynamic imports. If there are non critical components needed for a one-off builder page, wed prob just add the page directly to the codebase and import the registration

2025-01-15 19:13 UTC, olavoparno commented on src/utils/server/builder/models/page/utils/getPageContent.ts
> +export function getPageContent(pageModelName: PageModelIdentifiers, pathname: string) {
should we turn this function into async?

2025-01-15 19:17 UTC, olavoparno submitted a review, later dismissed

2025-01-15 19:19 UTC, travisbloom-cb approved these changes

2025-01-15 19:19 UTC, travisbloom-cb commented on src/app/(builder)/[locale]/content/[[...page]]/page.tsx
> +    .getAll(PAGE_MODEL, { options: { noTargeting: true } })
This will need to be changed as soon as we have builder.io pages that arent prefixed with /content/. Can't we just filter for builder.io pages that start with /content/?

2025-01-15 19:19 UTC, travisbloom-cb commented on src/app/(builder)/[locale]/layout.tsx
> +import { SpeedInsights } from '@vercel/speed-insights/next'
smart usage of next.js folder apis 👍

2025-01-15 19:19 UTC, travisbloom-cb commented on src/components/app/builder.tsx
> +  if (props.type === 'section') {
is this still needed?

2025-01-15 19:19 UTC, travisbloom-cb commented on src/components/app/builder.tsx
> +  return notFound()
this should prob log to sentry?

2025-01-15 19:19 UTC, travisbloom-cb commented on src/utils/server/builder/models/data/constants.ts
> +export enum DataModelIdentifiers {
`BuilderDataModelIdentifiers`

2025-01-15 19:19 UTC, travisbloom-cb commented on src/utils/server/builder/models/page/constants.ts
> +export enum PageModelIdentifiers {
`BuilderPageModelIdentifiers`

2025-01-15 19:19 UTC, travisbloom-cb commented on src/utils/server/builder/models/page/utils/getPageContent.ts
> +      cachebust: true,
when would this be false?

2025-01-15 19:19 UTC, travisbloom-cb commented on src/utils/server/builder/models/page/utils/getPageDetails.ts
> +    hasFooter: content?.data?.hasFooter ?? true,
can we set this to default within builder.io UI? Confusing it could be unchecked in UI but true here

2025-01-15 19:26 UTC, lucasrmp-cb commented on src/components/app/builder.tsx
> +  return notFound()
If this uses the default not found page it already handles logging and mixpanel events

2025-01-15 19:36 UTC, twistershark commented on src/utils/server/builder/models/page/constants.ts
> +export enum PageModelIdentifiers {
+1

2025-01-15 19:39 UTC, twistershark commented on src/utils/server/builder/models/data/constants.ts
> +export enum DataModelIdentifiers {
+1

2025-01-15 19:40 UTC, lucasrmp-cb commented on src/utils/server/builder/models/page/utils/getPageDetails.ts
> +    hasNavbar: content?.data?.hasNavbar ?? true,
Same here

2025-01-15 20:00 UTC, twistershark commented on src/app/(builder)/[locale]/content/[[...page]]/page.tsx
What is your opinion on having the builder io group folder inside our current [locale] folder instead of creating another folder at the root level?

it would be something like 

[locale]
  (builder)
    content
    ...

2025-01-15 20:05 UTC, twistershark commented on src/app/(builder)/[locale]/content/[[...page]]/page.tsx
Also, I'm not sure if we want to keep the "/content" segment on Builder.io pages, but I think we could move the [[...page]] folder to the same level as our other pages. NextJS will prioritize loading content from non-dynamic folders, and if none is found, it will fallback to dynamic folders (routes) if they exist. 

Since you are checking if the page exists in Builder.io, we would still show 404 pages when it doesn’t exist.

2025-01-15 20:21 UTC, LucasdRossi commented on src/utils/server/builder/models/page/utils/getPageDetails.ts
> +    hasFooter: content?.data?.hasFooter ?? true,
Yes, the default value is `true` in Builder.io, this `?? true` will only be applied if `content?.data?.hasFooter` is `undefined`

![image](https://github.com/user-attachments/assets/e2694b75-9364-49ef-bf40-cda228de3dba)

If the checkbox is unchecked, this value will be false

2025-01-15 20:22 UTC, LucasdRossi commented on src/utils/server/builder/models/page/utils/getPageContent.ts
> +export function getPageContent(pageModelName: PageModelIdentifiers, pathname: string) {
I don't think we should, because we don't need to await for anything to return the content

2025-01-15 20:31 UTC, LucasdRossi commented on src/app/(builder)/[locale]/content/[[...page]]/page.tsx
> +    .getAll(PAGE_MODEL, { options: { noTargeting: true } })
This is only getting pages within the `content` page model, so it's already fetching pages that start with `/content/` because `PAGE_MODEL = content`.

When we add pages to the default page model they won't be fetched here, because they belong to another page model

2025-01-16 17:01 UTC, LucasdRossi commented on src/utils/server/builder/models/page/utils/getPageContent.ts
> +      cachebust: true,
This is what the [official doc](https://www.builder.io/c/docs/content-api#code-cachebust-code) says
![image](https://github.com/user-attachments/assets/b800e770-ad1c-4756-90e3-69df121d119d)

2025-01-16 17:04 UTC, LucasdRossi commented on src/components/app/builder.tsx
> +  return notFound()
It's using the default not found page, but do you guys think we should log a different type of error?

2025-01-16 17:34 UTC, LucasdRossi commented on src/app/(builder)/[locale]/content/[[...page]]/page.tsx
> +        page: path.replace(PAGE_PREFIX, '').split('/'),
The Builder.io response already includes the page prefix, but Next.js only requires the slug (without the prefix) to correctly generate static pages. That's why the path is adjusted here.

2025-01-16 21:46 UTC, LucasdRossi commented on src/app/(builder)/[locale]/content/[[...page]]/page.tsx
Thank you for the great feedback, Paulo!

**Regarding the route grouping:**
We grouped the pages this way because Builder.io pages need to control whether the Navbar and Footer are displayed based on their configuration. To achieve this, we require the page’s pathname, which is not accessible in the Layout. Hence, we introduced the BuilderPageLayout component as a top-level component for Builder.io pages. This component registers and renders the Navbar and Footer conditionally, avoiding duplication. The Builder.io folder layout does not include fixed Navbar and Footer to preserve the existing layout structure without modifying all pages to add separate top-level components for these elements.

**Regarding removing the /content prefix:**
This is a valid approach, but it limits control over dynamic entries in the application. Without the prefix, managing content in Builder.io becomes more challenging, as we’d have to rely on a single, general Page Model. By keeping defined dynamic points like /blog, /content, or /press, each with its own Page Model in Builder.io, we improve maintainability and allow for specific configurations for each type of page.

Let me know your thoughts!

2025-01-17 18:33 UTC, olavoparno submitted a review, later dismissed

2025-01-17 20:44 UTC, twistershark commented on src/app/(builder)/[locale]/content/[[...page]]/page.tsx
Got it! Great work!

2025-01-17 20:44 UTC, twistershark submitted a review, later dismissed

2025-01-20 14:52 UTC, lucasrmp-cb submitted a review, later dismissed

2025-01-20 16:47 UTC, lucasrmp-cb approved these changes

2025-01-20 16:55 UTC, merged