[feat] Make full row in the politician table clickable
Stand-With-Crypto/swc-web pull request #630
Opened 2024-03-08 22:04 UTC by kl-cb

**What changed? Why?**

Allow user to click anywhere on the politician table row to navigate to politician page

**UI changes**
None

**PlanetScale Deploy Request**

**Notes to reviewers**

**How has it been tested?**

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

**Change management**
type=routine 
risk=low 
impact=sev5

2024-03-08 22:35 UTC, lucasrmp-cb reviewed
We already tried twice to do this, first @travisbloom-cb and then me, both times we got a weird and hard to reproduce bug where the politician page would randomly open for no apparent reason.
@travisbloom-cb what do you think? Third time is the charm?

2024-03-09 00:15 UTC, travisbloom-cb commented
Just QAed on safari mobile, same problem :(

2024-03-11 13:07 UTC, travisbloom-cb requested changes
The bug is that when you click a filter on mobile, it will jump to a persons page. I assume this happens because the browser thinks the click is for the popover and the element below. We need to investigate radix github issues to see if theres a pending issue/known fix

2024-03-11 21:00 UTC, travisbloom-cb requested changes

2024-03-11 21:00 UTC, travisbloom-cb commented on src/components/app/dtsiClientPersonDataTable/dataTable.tsx
> +                      openWindow(getIntlUrls(locale).politicianDetails(row.original.slug))
we want to use router.push for this

2024-03-11 21:00 UTC, travisbloom-cb commented on src/components/app/dtsiClientPersonDataTable/columns.tsx
> -        <InternalLink
will it break if we leave this? better for accessibility :)

2024-03-11 21:00 UTC, travisbloom-cb commented on src/components/app/dtsiClientPersonDataTable/globalFiltersUtils.tsx
> +          ref={ref => {
O_o

2024-03-11 21:01 UTC, travisbloom-cb commented
Appears to still be broken on chrome https://swc-web-git-kaerah-politician-row-click-stand-with-crypto.vercel.app/politicians :(

2024-03-12 21:38 UTC, kl-cb commented on src/components/app/dtsiClientPersonDataTable/columns.tsx
> -        <InternalLink
Added it back

2024-03-12 21:45 UTC, kl-cb commented
> Appears to still be broken on chrome https://swc-web-git-kaerah-politician-row-click-stand-with-crypto.vercel.app/politicians :(

I cannot reproduce the bug on iphone safari and chrome, and android chrome. @travisbloom-cb  Can your share what steps you are doing to get the bug?

2024-03-12 22:30 UTC, travisbloom-cb commented
> > Appears to still be broken on chrome https://swc-web-git-kaerah-politician-row-click-stand-with-crypto.vercel.app/politicians :(
> 
> I cannot reproduce the bug on iphone safari and chrome, and android chrome. @travisbloom-cb Can your share what steps you are doing to get the bug?

Go to [this url](https://swc-web-git-kaerah-politician-row-click-stand-with-crypto.vercel.app/politicians) on chrome, set your browser dimensions to iPhone XR, scroll down so the filters are fixed over the table, and then select the stance on crypto filter and select "Pending".


https://github.com/Stand-With-Crypto/swc-web/assets/153657370/a49da53e-d754-4bd0-b6ec-d83288dba3ee

2024-03-13 16:03 UTC, kl-cb commented
@travisbloom-cb I followed your steps and after i did a hard refresh on the page, i did not reproduce the bug. I think it does not have the latest code changes from when you last accessed the page.


https://github.com/Stand-With-Crypto/swc-web/assets/108414827/f4757c4c-8b20-49b5-a448-804514ca5956

2024-03-13 18:28 UTC, travisbloom-cb commented
> @travisbloom-cb I followed your steps and after i did a hard refresh on the page, i did not reproduce the bug. I think it does not have the latest code changes from when you last accessed the page.
> 
>  Screen.Recording.2024-03-13.at.12.00.52.PM.mov

Super weird. Lets sync on it during our one on one.

2024-03-13 19:38 UTC, travisbloom-cb approved these changes

2024-03-13 20:36 UTC, merged