Autopopulate politician page with address query param
Stand-With-Crypto/swc-web pull request #649
Opened 2024-03-11 21:19 UTC by kl-cb

**What changed? Why?**

**UI changes**

_Web_

| Old 👴         | New 👶         |
| -------------- | -------------- |
| old screenshot | new screenshot |

_Mobile Web_

| Old 👴         | New 👶         |
| -------------- | -------------- |
| old screenshot | new screenshot |

**PlanetScale Deploy Request**

**Notes to reviewers**

**How has it been tested?**

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

**Change management**
type=routine 
risk=low 
impact=sev5

2024-03-12 17:51 UTC, travisbloom-cb requested changes
I might be doing something wrong but is not working for me :( https://swc-4lx4kwjiv-stand-with-crypto.vercel.app/politicians?address=70%20west%2093rd%20st%20apt%2025g%20ny%20ny

2024-03-12 17:51 UTC, travisbloom-cb commented on src/components/app/clientCurrentUserDTSIPersonCardOrCTA.tsx
> +    return <Skeleton className="h-[120px] w-full" />
causes a weird render state for users coming to the page without an address. Can we just return the default component instead?

2024-03-12 17:51 UTC, travisbloom-cb commented on src/components/app/clientCurrentUserDTSIPersonCardOrCTA.tsx
> +  console.log('ready', ready, 'addressSuggestions', addressSuggestions)
^^^

2024-03-12 20:30 UTC, travisbloom-cb requested changes
@kl-cb I still think the two issue i flagged aren't addressed :(

2024-03-12 21:07 UTC, kl-cb commented
> @kl-cb I still think the two issue i flagged aren't addressed :(

Weird. It is working for me locally


https://github.com/Stand-With-Crypto/swc-web/assets/108414827/83199f8a-c05e-4215-b570-ec573985adcc

2024-03-12 21:11 UTC, kl-cb commented
This is the page load without an address query param 


https://github.com/Stand-With-Crypto/swc-web/assets/108414827/1986ff83-7274-4b1e-9036-24515e624c80

2024-03-12 22:25 UTC, travisbloom-cb requested changes

2024-03-12 22:25 UTC, travisbloom-cb commented on src/components/app/pagePoliticians/index.tsx
> +        <Suspense>
Still getting a weird render issue where the address doesnt show up on initial load. I think its because we need a fallback here that just renders the component without the query param hook

2024-03-13 18:18 UTC, travisbloom-cb requested changes
@kl-cb in production, if I add an address, then reload the page, it saves in session and autopopulates. I think this functionality is broken now in this branch. [This logic](https://github.com/Stand-With-Crypto/swc-web/blob/main/src/components/app/clientCurrentUserDTSIPersonCardOrCTA.tsx#L31)

2024-03-13 18:51 UTC, kl-cb commented
> ?address=1998%20Broadway%2C%20New%20York%2C%20NY%2010023

@travisbloom-cb it should be fixed now. It will prioritize the query param.

2024-03-13 22:29 UTC, travisbloom-cb approved these changes

2024-03-14 14:12 UTC, merged