Add a script we can run to backfill any missing nft mints
Stand-With-Crypto/swc-web pull request #665
Opened 2024-03-13 19:31 UTC by ydruffin-cb

closes https://github.com/Stand-With-Crypto/swc-web/issues/653

**What changed? Why?**
Added an inngest function to backfill NFTs because the functionality was turned off and we need to mint all the NFT of the actions performed during that time.

**Notes to reviewers**
Please pay attention to the Prisma request in src/bin/oneTimeScripts/backfillNFT.ts to be sure that I got it right.

**How has it been tested?**

- [ ] Locally
- [ ] Vercel Preview Branch

**Change management**
type=routine 
risk=low 
impact=sev5

2024-03-13 22:28 UTC, benson-budiman-cb commented on src/inngest/functions/backfillNT.ts
> +import { onScriptFailure } from '@/inngest/onScriptFaillure'
nit: there's also a type here - `onScriptFaillure`

2024-03-13 22:28 UTC, benson-budiman-cb commented on src/inngest/functions/backfillNT.ts
> +)
nit: this filename has a typo - `backfillNT`

2024-03-13 22:28 UTC, travisbloom-cb requested changes

2024-03-13 22:28 UTC, travisbloom-cb commented on src/bin/oneTimeScripts/backfillNFT.ts
> +const ACTION_WITH_NFT: UserActionType[] = [
We should use [this logic](https://github.com/Stand-With-Crypto/swc-web/blob/main/src/utils/server/nft/claimNFT.ts#L27) to determine what Actions have nfts

2024-03-13 22:28 UTC, travisbloom-cb commented on src/bin/oneTimeScripts/backfillNFT.ts
> +export async function backfillNFT(parameters: z.infer<typeof zodBackfillNFParameters>) {
We prob want fns like this (and the last one) to not be in bin because they arent bin files. Maybe you create`src/inngest/functions/backfillNT/logic.tsx` for this stuff and the actual inggest fn is `src/inngest/functions/backfillNT/index.tsx`

2024-03-13 22:28 UTC, travisbloom-cb commented on src/bin/oneTimeScripts/backfillNFT.ts
> +    promises.push(claimNFT(userAction, userAction.user.primaryUserCryptoAddress!, true))
we need to batch these prob https://github.com/Stand-With-Crypto/swc-web/blob/main/src/utils/shared/batchAsyncAndLog.ts#L5

2024-03-13 22:28 UTC, travisbloom-cb commented on src/utils/server/nft/claimNFT.ts
> +  ignoreTurnOffNFTMintFlag: boolean = false,
lets use a config arg here so its clear

2024-03-13 22:41 UTC, ydruffin-cb commented on src/bin/oneTimeScripts/backfillNFT.ts
> +const ACTION_WITH_NFT: UserActionType[] = [
haha, I tried, but I had some difficulties to get a UserActionType from that, 
Ok let me try again

2024-03-13 22:42 UTC, ydruffin-cb commented on src/bin/oneTimeScripts/backfillNFT.ts
> +export async function backfillNFT(parameters: z.infer<typeof zodBackfillNFParameters>) {
tsx ?
I guess you meant .ts

2024-03-14 00:02 UTC, ydruffin-cb commented on src/bin/oneTimeScripts/backfillNFT.ts
> +    promises.push(claimNFT(userAction, userAction.user.primaryUserCryptoAddress!, true))
✔️

2024-03-14 00:03 UTC, ydruffin-cb commented on src/bin/oneTimeScripts/backfillNFT.ts
> +export async function backfillNFT(parameters: z.infer<typeof zodBackfillNFParameters>) {
✔️

2024-03-14 00:03 UTC, ydruffin-cb commented on src/bin/oneTimeScripts/backfillNFT.ts
> +const ACTION_WITH_NFT: UserActionType[] = [
✔️

2024-03-14 00:18 UTC, ydruffin-cb commented on src/utils/server/nft/claimNFT.ts
> +  ignoreTurnOffNFTMintFlag: boolean = false,
Ok I did add a config arg, not sure it is what you had in mind, let me know

2024-03-14 01:04 UTC, merged