Update docs to OS contributors
Stand-With-Crypto/swc-web pull request #685
Opened 2024-03-18 15:15 UTC by lucasrmp-cb

closes #252 

## What changed? Why?

## UI changes

### Web

| Old 👴         | New 👶         |
| -------------- | -------------- |
| old screenshot | new screenshot |

### Mobile Web

| Old 👴         | New 👶         |
| -------------- | -------------- |
| old screenshot | new screenshot |

## PlanetScale Deploy Request

## Notes to reviewers

## How has it been tested?

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

## Change management
type=routine 
risk=low 
impact=sev5

2024-03-19 12:58 UTC, travisbloom-cb requested changes

2024-03-19 12:58 UTC, travisbloom-cb commented on .env.example
> +# If you need to access any features that wont work because of missing env vars, reach out to a core contributor
`If you need to access any features that wont work because of missing env vars, follow the comments to add them`

2024-03-19 12:58 UTC, travisbloom-cb commented on README.md
> -### Development pre-requisites
because its hard to diff, can you verify what sections here weren't moved over to contributing?

2024-03-19 12:58 UTC, travisbloom-cb commented on package.json
> +    "prisma": "^5.11.0",
any reason we did this in this pr?

2024-03-19 12:58 UTC, travisbloom-cb commented on package.json
> -    "precheck": "concurrently \"next lint --max-warnings=0 --fix\"  \"prettier --log-level silent --write .\" \"npm run typecheck\" \"npm run test -- -u\"",
this is different. Precheck used to write the changes, now it doesn't :(

2024-03-19 12:58 UTC, travisbloom-cb commented on src/utils/server/prismaClient.ts
> +    process.env.LOG_DATABASE === 'true'
https://github.com/Stand-With-Crypto/swc-web/blob/fix-unmatched-dtsi-to-google-civic/src/utils/shared/toBool.ts#L1

2024-03-19 12:58 UTC, travisbloom-cb commented on src/utils/shared/requiredEnv.ts
> +        `Environment variable ${name} is missing. Some functionalities may not work properly`,
we might want a third arg here which is a string explaining the functionality that won't work without this env var. A little more descriptive

2024-03-19 13:12 UTC, lucasrmp-cb commented on package.json
> +    "prisma": "^5.11.0",
I didn't actually, not sure how this happened lol

2024-03-19 13:16 UTC, lucasrmp-cb commented on README.md
> -### Development pre-requisites
The only removed information is `Local Development > Running One Time Scripts > Locally`, a lot of stuff has been rewritten and I added a lot of stuff

2024-03-19 14:42 UTC, travisbloom-cb requested changes

2024-03-19 14:42 UTC, travisbloom-cb commented on .env.example
> +NEXT_PUBLIC_MIXPANEL_PROJECT_TOKEN=
shouldnt this be optional?

2024-03-19 14:42 UTC, travisbloom-cb commented on docs/Contributing.md
> +Before proceeding with anything, **PLEASE** check out this following resources.
This was really only needed when I was onboarding new team members. we can soften the language:
```suggestion
Below is a list of suggested documentation to read through if you aren't already familiar with the technologies used in this repository:
```

2024-03-19 14:42 UTC, travisbloom-cb commented on docs/Contributing.md
> +- Open the `.env` file and update the values if needed based on the commented instructions
Maybe we move this to be after open localhost:300 and modify to 

```suggestion
- Optional: Open the  `.env` file and update excluded values if the functionality is needed for the feature your working on
```

2024-03-19 14:42 UTC, travisbloom-cb commented on docs/Contributing.md
> +- Run `$ npm run initial`, that includes all setup commands for first-time local development
```suggestion
- Run `$ npm run initial`, this includes all setup commands for first-time local development
```

2024-03-19 14:42 UTC, travisbloom-cb commented on docs/Contributing.md
> +  - `npm run test` - execute Jest tests
```suggestion
  - `npm run test` - executes Jest tests
```

2024-03-19 14:42 UTC, travisbloom-cb commented on docs/Contributing.md
> +    - If `audit` fails, then it is very likely that your PR will not pass GitHub CI
```suggestion
    - If `audit` fails, your PR will not pass GitHub CI
```

2024-03-19 14:42 UTC, travisbloom-cb commented on docs/Contributing.md
> +    - Currently, this command only executes when new comments are made to main branch because of database dependencies - this may change in the future
we can get rid of this i think

2024-03-19 14:42 UTC, travisbloom-cb commented on docs/Contributing.md
> +- `npm run codegen:schemas` - if any of the GraphQL schemas changed for our 3rd-party API partners (_e.g._ https://www.dotheysupportit.com/), run this command to pull in the latest schemas
```suggestion
- `npm run codegen:schemas` - if any of the GraphQL schemas change for our 3rd-party API partners (_e.g._ https://www.dotheysupportit.com/), run this command to pull in the latest updates
```

2024-03-19 14:42 UTC, travisbloom-cb commented on docs/Contributing.md
> +- When checking out someone else's branch with changes - if you encounter TypeScript errors, run `npm run newbranch` to execute several common commands that may fix these errors
```suggestion
-`npm run newbranch` - A useful command to run after checking out a newbranch or pulling the latest from `main` to ensure your local environment is configured correctly
```

2024-03-19 14:42 UTC, travisbloom-cb commented on docs/Contributing.md
> +  - `npm run db:seed` - if you do have breaking changes, or if you just want to reset your database values, then run this command; this command force-pushes the schema updates to the database instanc
We should only include `npx prisma db push` as an option moving forward

2024-03-19 14:42 UTC, travisbloom-cb commented on docs/Contributing.md
> +### Running One Time Scripts On Testing or Production Environment
```suggestion
### Running One Time Scripts in Testing or Production Environment
```

2024-03-19 14:42 UTC, travisbloom-cb commented on docs/Contributing.md
> +On a testing or production environment, it is recommended to run the script through Inngest admin dashboard:
```suggestion
In our testing or production environment, it is recommended to run a script through the Inngest admin dashboard:
```

2024-03-19 14:42 UTC, travisbloom-cb commented on docs/Contributing.md
> +- Click the invoke button in the right corner
```suggestion
- Click the invoke button in the top right corner
```

2024-03-19 14:42 UTC, travisbloom-cb commented on src/utils/server/redis.ts
> +  token: UPSTASH_REDIS_REST_TOKEN ?? 'UPSTASH_REDIS_REST_TOKEN',
why is this needed? we should add a comment explaining

2024-03-19 14:42 UTC, travisbloom-cb commented on src/utils/web/clientAnalytics.ts
>  const NEXT_PUBLIC_MIXPANEL_PROJECT_TOKEN = requiredEnv(
requiredOutsideLocalEnv right?

2024-03-19 15:37 UTC, lucasrmp-cb commented on docs/Contributing.md
> +- Open the `.env` file and update the values if needed based on the commented instructions
I agree we should add it, but I don't get why remove this one here, they have different purposes

2024-03-19 16:04 UTC, lucasrmp-cb commented on docs/Contributing.md
> +- Click the invoke button in the right corner
They do need to fill everything that is blank and not bellow the "Optional" title, I'll make it clearer with something like:
```Open the `.env` file and fill all the blank values that are not bellow the `OPTIONAL` title. Follow the commented instructions for each one```

2024-03-19 16:04 UTC, lucasrmp-cb commented on docs/Contributing.md
> +- Open the `.env` file and update the values if needed based on the commented instructions
They do need to fill everything that is blank and not bellow the "Optional" title, I'll make it clearer with something like:
```Open the `.env` file and fill all the blank values that are not bellow the `OPTIONAL` title. Follow the commented instructions for each one```

2024-03-19 16:13 UTC, travisbloom-cb commented on docs/Contributing.md
> +- Open the `.env` file and update the values if needed based on the commented instructions
Gotcha, didn't realize they were required 👍

2024-03-19 16:14 UTC, travisbloom-cb commented on .env.example
> +# You can get this by creating a project through google console, see https://support.google.com/googleapi/answer/6158862?hl=en
"Your project API key will need access to the following APIs:
- Google Civic Information API
- Places API (New)
- Places API
"

2024-03-19 19:21 UTC, travisbloom-cb commented on src/mocks/dtsi/mockResolvers/dtsiPersonRoleResolver.ts
> +    roleCategory === DTSI_PersonRoleCategory.PRESIDENT && !overrides.roleCategory
shouldnt this be used to replace roleCategory above? 

```
const roleCategory = overrides.roleCategory || faker.helpers.arrayElement...
```

2024-03-19 19:29 UTC, lucasrmp-cb commented on src/mocks/dtsi/mockResolvers/dtsiPersonRoleResolver.ts
> +    roleCategory === DTSI_PersonRoleCategory.PRESIDENT && !overrides.roleCategory
It could, but because of typing `overrides.roleCategory` is a function that is expecting to receive a `parent` and we don't have access to that in this context

2024-03-19 19:29 UTC, travisbloom-cb submitted a review, later dismissed

2024-03-19 20:45 UTC, kl-cb commented on .env.example
> +# If you need to access any features that wont work because of missing env vars, follow the comments to add them
`won't`

2024-03-19 20:46 UTC, kl-cb commented on .env.example
> +# - Places API
What's the difference between these two?

2024-03-19 20:46 UTC, kl-cb commented on .env.example
> +# The wallet does not need to have any funds.
`server-side checks` ?

2024-03-19 21:01 UTC, benson-budiman-cb commented on .env.example
> +# These values can be generated by creating a free account and generating your own url and token at https://upstash.com/docs/redis/howto/connectwithupstashredis
```suggestion
# These values can be generated by creating a personal free account and generating your own UPSTASH_REDIS_REST_URL and UPSTASH_REDIS_REST_TOKEN via https://console.upstash.com/redis
# - Go to the link above, and create your own personal account.
# - Create your own personal Redis database with any name you want. Set the region to `us-east-1`. You can leave any other settings untouched.
# - Once the Redis database is created, go to its details and scroll down. You should see the URL and the token.
```

2024-03-19 21:08 UTC, benson-budiman-cb commented on .env.example
> +# These values can be generated by creating a free account and getting the token at https://mixpanel.com/settings/project/
```suggestion
# These values can be generated by creating a free Mixpanel account, creating a new Mixpanel project, then copy-pasting the "Project Token" from https://mixpanel.com/settings/project/
```

2024-03-19 21:11 UTC, benson-budiman-cb commented on .env.example
> +# - Places API
https://developers.google.com/maps/documentation/places/web-service/choose-api

But I also have a question - what do we have that relies on the "old" Places API? and can we migrate that to use the Places API (New)?

2024-03-19 21:16 UTC, benson-budiman-cb commented on .env.example
> +LOCAL_USER_CRYPTO_ADDRESS="0x000000000000000000"
Maybe use the full length `0x0000000000000000000000000000000000000000`?

2024-03-19 21:16 UTC, benson-budiman-cb commented on .env.example
> +# Verified partner secret keys
Should they leave as is?

2024-03-19 21:17 UTC, benson-budiman-cb commented on .env.example
> +# These values are here as dummys for database seed
Should they leave as is? Also should we use the full length null ETH wallet address?

2024-03-19 21:18 UTC, benson-budiman-cb commented on .env.example
> +# We use BaseScan to check transaction fees
```suggestion
# We use BaseScan to check transaction fees. If you need this, generate your own BaseScan API key at https://basescan.org/myapikey
```

2024-03-19 21:29 UTC, benson-budiman-cb commented on docs/Contributing.md
> +If you have questions about implementation details, help or support, then please use our dedicated community forum at [GitHub Discussions](https://github.com/Stand-With-Crypto/swc-web/discussions) PL
Oxford comma - `implementation details, help, or support`

2024-03-19 21:30 UTC, benson-budiman-cb commented on docs/Contributing.md
> +If you have questions about implementation details, help or support, then please use our dedicated community forum at [GitHub Discussions](https://github.com/Stand-With-Crypto/swc-web/discussions) PL
```suggestion
If you have questions about implementation details, help, or support, then please use our dedicated community forum at [GitHub Discussions](https://github.com/Stand-With-Crypto/swc-web/discussions). PLEASE NOTE: If you choose to instead open an issue for your question, your issue will be immediately closed and redirected to the forum.
```

2024-03-19 21:31 UTC, benson-budiman-cb commented on docs/Contributing.md
> +If you have found what you think is a bug, please [file an issue](https://github.com/Stand-With-Crypto/swc-web/issues/new). PLEASE NOTE: Issues that are identified as implementation questions or non-
If you have found what you think is a bug, please [file an issue](https://github.com/Stand-With-Crypto/swc-web/issues/new). PLEASE NOTE: Issues that are identified as implementation questions or non-issues will be immediately closed and redirected to [GitHub Discussions](https://github.com/Stand-With-Crypto/swc-web/discussions)
```suggestion
If you have found what you think is a bug, please [file an issue](https://github.com/Stand-With-Crypto/swc-web/issues/new). PLEASE NOTE: Issues that are identified as implementation questions or non-issues will be immediately closed and redirected to [GitHub Discussions](https://github.com/Stand-With-Crypto/swc-web/discussions).
```

2024-03-19 21:38 UTC, benson-budiman-cb requested changes

2024-03-19 21:38 UTC, benson-budiman-cb commented on docs/Contributing.md
> +  - We use docker-compose to run services both in local dev and in e2e testing
The Docker file for the local service and the Docker file for Cypress uses the same port for their MySQL database, right?

I think we should have a separate port for the Cypress MySQL database because some of the Cypress tests involve wiping the MySQL database to have a fresh database, and we probably do not want to unintentionally wipe the user's service database if they run the Cypress suite.

2024-03-20 01:07 UTC, ydruffin-cb commented on README.md
i feel like this Readme needs a bit more information and context. This is the entry point of the project. It feels extremely empty now

2024-03-20 15:15 UTC, lucasrmp-cb commented on .env.example
> +# - Places API
There's a new google places api that Google considers a different api in the console, you have to check them both

2024-03-20 15:19 UTC, lucasrmp-cb commented on .env.example
> +# Verified partner secret keys
Doesn't matter for OS contributors, they won't be able to run any CB integrations

2024-03-20 15:33 UTC, lucasrmp-cb commented on .env.example
> +# These values are here as dummys for database seed
Airdrop and a few other stuff wont work properly, but they don't need for most of the contributions. These are here as dummy only bc our db schema requires

2024-03-20 16:36 UTC, ydruffin-cb approved these changes

2024-03-20 17:07 UTC, benson-budiman-cb approved these changes
🔥 🔥 🔥 🔥 🚀 🚀 🚀 🚀 🚀

2024-03-21 21:25 UTC, kl-cb commented on README.md
I think it makes sense to put these sections in the main readme. I feel like the contributing doc is more for information to contribute code than giving feedback/suggestions/reporting bugs. 
<img width="521" alt="Screenshot 2024-03-21 at 5 12 25 PM" src="https://github.com/Stand-With-Crypto/swc-web/assets/108414827/b174dff1-6cc6-4d76-a68a-73d5074d2e49">

2024-03-22 14:41 UTC, merged