Handle undefined result from action
Stand-With-Crypto/swc-web pull request #694
Opened 2024-03-19 23:44 UTC by ydruffin-cb

closes https://github.com/Stand-With-Crypto/swc-web/issues/670
fixes [PROD-SWC-WEB-18Q](https://stand-with-crypto.sentry.io/issues/5029315222/?referrer=github_integration)

**What changed? Why?**
I added a check of the result of an action in withServerActionMiddleware function and throw an error if the result is undefined. This is to avoid reading a field of an undefined result on the client side.

**Notes to reviewers**
I don't think I fully master the promises in javascript. So I an not fully confident of my solution here. 

**How has it been tested?**

- [ ] Locally
- [ ] Vercel Preview Branch

**Change management**
type=routine 
risk=low 
impact=sev5

2024-03-20 16:28 UTC, lucasrmp-cb requested changes

2024-03-20 16:28 UTC, lucasrmp-cb commented on src/utils/server/withServerActionMiddleware.ts
> +        return promise
Few things to note here:
1. Putting a `.catch` suppresses all internal server errors the actions might want to throw, you are logging and then returning `undefined` for the request 
2. Since you're suppressing errors (including the one you are throwing in line 42) this request will continue to respond with undefined. If the idea is to fail the request if the result is `undefined` removing the `.catch` will work properly
3. If you wanna log the error anyways, just throw the error inside the `.catch` scope
```typescriptreact
.catch(error => {
  logger.error(error)
  throw error
})
```
4. On the `.catch` syntax, we shouldn't use anonymous functions with the `function` keyword (they should be arrow functions) and you don't need to specify a type for the error.
5. You can do all of this inline, `.then` and `.catch` return the promise itself, you can do `return action(...).then(...).catch(...)` normally

2024-03-21 15:47 UTC, ydruffin-cb commented on src/utils/server/withServerActionMiddleware.ts
> +        return promise
yes, this is why I found my solution weird, but without the catch, I receive an  error that I am throwing an error on an async function without a catch and got unhandled error in Sentry. So in the end I remove one error by replacing by another one... 😕
For the 4th point, I end up using an anonymous function because my IDE keep complaining about that I didn't specify an error type 🤷‍♂️

Anyway I am going to try couple of your suggestion

2024-03-21 19:55 UTC, lucasrmp-cb approved these changes

2024-03-21 19:58 UTC, travisbloom-cb requested changes

2024-03-21 19:58 UTC, travisbloom-cb commented on src/components/app/userActionFormCallCongressperson/sections/suggestedScript.tsx
> +        toastGenericError()
dont we show an error with setCallingState('error')

2024-03-21 21:00 UTC, ydruffin-cb commented on src/components/app/userActionFormCallCongressperson/sections/suggestedScript.tsx
> +        toastGenericError()
right

2024-03-21 21:53 UTC, travisbloom-cb approved these changes

2024-03-21 21:57 UTC, merged