feat: skip address step when user has an address
Stand-With-Crypto/swc-web pull request #705
Opened 2024-03-21 19:42 UTC by lucasrmp-cb

closes #454 
fixes 

**What changed? Why?**

**UI changes**

_Web_

| Old 👴         | New 👶         |
| -------------- | -------------- |
| old screenshot | new screenshot |

_Mobile Web_

| Old 👴         | New 👶         |
| -------------- | -------------- |
| old screenshot | new screenshot |

**PlanetScale Deploy Request**

**Notes to reviewers**

**How has it been tested?**

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

**Change management**
type=routine 
risk=low 
impact=sev5

2024-03-22 15:24 UTC, lucasrmp-cb commented on src/app/[locale]/layout.tsx
> +        ></script>
This is necessary so we can do `getDetails`, before the call would work only if at some point we rendered an address input before trying to call it. This way we have the sdk being loaded in the client and since it's being deferred we shouldn't have any impact on performance

2024-03-22 19:46 UTC, benson-budiman-cb commented on cypress.config.ts
> +  defaultCommandTimeout: 20000,
Looking at the result of the GitHub Actions' Cypress test, I do not think increasing the timeout of the command helped. There's probably something flaky that happens right before the individual commands.

2024-03-22 19:52 UTC, travisbloom-cb requested changes

2024-03-25 12:48 UTC, lucasrmp-cb commented on src/app/[locale]/layout.tsx
> +        <Script
2 reasons:

1. Next optimizes this loading a lot, we can either defer the loading to when the browser is idle, after interactive or (experimental for now) even load it in a completely separated worker thread, I don't think the gain is significant enough to justify having to manually load and wait for it to be ready every time we need to use the api
2. In this use case for example I would need a loading state to wait for the script to load, It'd take even more time to load the modal then it already takes (being a lazy load component).

I'm not sure giving up multiple component loadings performance for an optimized loading on page load is the best way to go but maybe I'm underestimating how impactful it really is.

2024-03-26 14:45 UTC, travisbloom-cb commented on src/app/[locale]/layout.tsx
> +        <Script
can we add `strategy="lazyOnload"` then?

2024-03-26 16:53 UTC, lucasrmp-cb commented on src/app/[locale]/layout.tsx
> +        <Script
Sure, done!

2024-03-26 17:27 UTC, travisbloom-cb submitted a review, later dismissed

2024-04-04 14:59 UTC, travisbloom-cb submitted a review, later dismissed

2024-04-04 15:18 UTC, travisbloom-cb approved these changes

2024-04-04 15:44 UTC, merged