feature: migrate v1 inAppDonations to swc v2
Stand-With-Crypto/swc-web pull request #713
Opened 2024-03-22 19:21 UTC by jm-coinbase

closes 
fixes 

## What changed? Why?
This PR introduces `createInAppCharge` function copying functionality of backend endpoint for in app donations  from SwC V1.

@travisbloom-cb @lucasrmp-cb should this function also accept `userId` and `sessionId` like `createCharge`? I exposed `api/internal/in-app-donations`, not sure though if this is right approach if we're planning to add frontend to this feature.

It was tested via running local server and curling endpoint to hit commerce v2 api (I was only able to migrate my account to prod on commerce beta/api - commerce dev env still responds with v1 api):

`data_swc.json` file
```json
{
  "address": "My test address, 11-111",
  "email": "my-test-email@coinbase.com",
  "employer": "Coinbase",
  "full_name": "John Doe",
  "is_citizen": false,
  "occupation": "occupation test"
}
```
api responded with

```json
{"charge_url":"https://commerce.coinbase.com/pay/test_pay_id"
```
upon inspecting created commerce charge I was able to confirm that api stored fields correctly

```json
{
  "data": {
    "brand_color": "#122332",
    "brand_logo_url": "",
    "charge_kind": "WEB3",
    "code": "test code",
    "collected_email": true,
    "created_at": "2024-03-22T19:04:31Z",
    "description": "Donate to Crypto",
    "expires_at": "2024-03-24T19:04:31Z",
    "hosted_url": "https://commerce.coinbase.com/pay/test_id",
    "id": "test_id",
    "metadata": {
      "is_citizen": "false",
      "employer": "Coinbase",
      "full_name": "John Doe",
      "address": "My test address, 11-111",
      "occupation": "occupation test",
      "email": "my-test-email@coinbase.com"
    },
    "name": "John Doe",
    "organization_name": "",
    "payments": [],
    "pricing": {
      "local": {
        "amount": "0",
        "currency": "USD"
      },
      "settlement": {
        "amount": "0",
        "currency": "USDC"
      }
    },
    "pricing_type": "no_price",
    "redirects": {
      "cancel_url": "https://www.standwithcrypto.org",
      "success_url": "",
      "will_redirect_after_success": false
    },
    "support_email": "my-test-email@coinbase.com",
    "timeline": [
      {
        "status": "NEW",
        "time": "2024-03-22T19:04:31Z"
      }
    ],
    "web3_data": {
      "transfer_intent": null,
      "success_events": [],
      "failure_events": [],
      "contract_addresses": {
        "137": "address_1",
        "1": "address_2",
        "8453": "address_3"
      },
      "settlement_currency_addresses": {
        "137": "address_4",
        "1": "address_5",
        "8453": "address_6"
      },
      "subsidized_payments_chain_to_tokens": {},
      "contract_caller_request_id": ""
    },
    "web3_retail_payments_enabled": true
  }
}
```

Let me know if this requires more exhaustive testing / some additional changes

## UI changes

### Web

| Old 👴         | New 👶         |
| -------------- | -------------- |
| old screenshot | new screenshot |

### Mobile Web

| Old 👴         | New 👶         |
| -------------- | -------------- |
| old screenshot | new screenshot |

## PlanetScale Deploy Request

## Notes to reviewers

## How has it been tested?

- [x] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

## Change management

type=routine 
risk=low 
impact=sev5

2024-03-22 19:29 UTC, jm-coinbase commented
looking into test failures 👀

2024-03-22 19:36 UTC, benson-budiman-cb commented on src/utils/server/coinbaseCommerce/createCharge.ts
> +export async function createInAppCharge({createChargeParams}: {createChargeParams: CreateChargeParams}) {
is there a specific reason why the `createChargeParams` object is nested within an object? (_i.e._ why not do `createChargeParams(createChargeParams)`)

2024-03-22 19:39 UTC, benson-budiman-cb commented on src/utils/server/coinbaseCommerce/createCharge.ts
> +export interface CreateChargeParams {
should we rename this to be more explicit that it's for in-app donations? _e.g._ `CreateInAppChargeParams`

2024-03-22 19:40 UTC, benson-budiman-cb commented on src/utils/server/coinbaseCommerce/createCharge.ts
> +interface TransferIntentCallData {
prefix these interface names with `CreateChargeResponse` to keep the interface naming consistent in the file

2024-03-22 19:42 UTC, benson-budiman-cb reviewed
I think my concern here is associating the in-app donation with the SWC user.

I actually do not know what the in-app donation UI looks like - can any Retail user donate without signing up for SWC? If so, then that (might) lead to an influx of new SWC users create via donations.

2024-03-26 16:44 UTC, jm-coinbase commented on src/utils/server/coinbaseCommerce/createCharge.ts
> +export async function createInAppCharge({createChargeParams}: {createChargeParams: CreateChargeParams}) {
no specific reason just my inexperience 😓 changing 👍

2024-03-26 17:49 UTC, benson-budiman-cb commented
@jm-coinbase I think [this code pointer](https://github.com/Stand-With-Crypto/swc-web/pull/713/files#diff-08b6c6c71fc77420a3c4b3a31a04b86bea359799331a9bf80a5abdae0b8d26d1R9-R12) is being triggered now given the new app router route, which is causing the Cypress GitHub test to fail. However, it appears that COINBASE_COMMERCE_API_KEY is not a "required" environment variable according to the `.env.example`.

I think we should do the following:
- Use `requiredOutsideLocalEnv` instead of `requiredEnv` for COINBASE_COMMERCE_API_KEY to not block local development
- In `.env.example`, include _optional_ instructions on how to get their own Commerce API key (which is just going to commerce.coinbase.com and creating an account).
- Add the API key to the GitHub actions environment variables for Cypress (ask Travis for help on this)

2024-03-28 21:22 UTC, jm-coinbase commented on src/app/api/internal/in-app-donations/route.ts
> +  const params: CreateInAppChargeParams = {
corresponds to https://github.cbhq.net/infra/graphql-monolith/blob/cadd8bc6b32909a386e251a6d1e6618fc82d84c8/internal/graph/schema/mutations/mutation_crypto_advocacy.graphql#L142

2024-04-02 18:52 UTC, travisbloom-cb requested changes

2024-04-02 18:52 UTC, travisbloom-cb commented on src/app/api/internal/in-app-donations/route.ts
> +  const existingAction = await prismaClient.userAction.findFirst({
we can fetch the user directly here right? we dont need to fetch the action

2024-04-02 18:52 UTC, travisbloom-cb commented on src/app/api/internal/in-app-donations/route.ts
> +              isVerified: true,
false

2024-04-02 18:52 UTC, travisbloom-cb commented on src/app/api/internal/in-app-donations/route.ts
> +    if (existingEmail && !existingEmail.isVerified) {
its not a verified email so we can delete this

2024-04-02 18:52 UTC, travisbloom-cb commented on src/utils/server/coinbaseCommerce/createCharge.ts
> +        'X-CC-Api-Key': String(COINBASE_COMMERCE_API_KEY),
why was this needed?

2024-04-05 03:38 UTC, jm-coinbase commented on src/app/api/internal/in-app-donations/route.ts
> +  const existingAction = await prismaClient.userAction.findFirst({
true, fixing 👍

2024-04-05 03:39 UTC, jm-coinbase commented on src/app/api/internal/in-app-donations/route.ts
> +              isVerified: true,
I thought that user coming from signed flow from retail app would be treated as verified 🤔 changing ✅

2024-04-05 03:40 UTC, jm-coinbase commented on src/app/api/internal/in-app-donations/route.ts
> +    if (existingEmail && !existingEmail.isVerified) {
✅

2024-04-05 03:41 UTC, jm-coinbase commented on src/utils/server/coinbaseCommerce/createCharge.ts
> +        'X-CC-Api-Key': String(COINBASE_COMMERCE_API_KEY),
I think it was failing because I switched to use `requiredOutsideLocalEnv` function as per Benson suggestion, should I revert this change?

2024-04-05 15:19 UTC, travisbloom-cb commented on src/app/api/internal/in-app-donations/route.ts
> +              isVerified: true,
The issue is theres nothing "signed" about the flow :(. Its not permissioned

2024-04-05 15:20 UTC, travisbloom-cb approved these changes

2024-04-17 14:41 UTC, travisbloom-cb submitted a review, later dismissed

2024-04-17 15:02 UTC, lucasrmp-cb commented on src/app/api/internal/in-app-donations/route.ts
> +      // TODO typesafe against invalid fields
We should either do this or link to an open issue to fix it

2024-05-02 17:31 UTC, lucasrmp-cb approved these changes

2024-05-08 15:42 UTC, merged