[feature] implement Farcaster Frames for "Register to Vote" SWC action
Stand-With-Crypto/swc-web pull request #766
Opened 2024-04-10 21:51 UTC by benson-budiman-cb

closes #739 

## What changed? Why?

This PR implements the Farcaster Frame for the "Register to Vote" SWC action.

## UI changes

TODO

## PlanetScale Deploy Request

No schema changes.

## Notes to reviewers

- You can test the development Farcaster Frame via Warpcast here: https://warpcast.com/~/developers/frames?url=https%3A%2F%2Fswc-web-git-tay-frame-stand-with-crypto.vercel.app%2Fframes%2Fregister-to-vote (NOTE: you need a Warpcast account to access Warpcast).

## How has it been tested?

- [ ] Locally
- [X] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

## Change management

type=routine 
risk=low 
impact=sev5

2024-04-12 14:12 UTC, travisbloom-cb requested changes
Super interesting to see how frames work!

2024-04-12 14:12 UTC, travisbloom-cb commented on src/app/api/public/frames/register-to-vote/route.tsx
> +    input: {
Edit: based on the context below it looks like this is actually overridden? If thats the case maybe we add a comment next to `target: 'https://www.usa.gov/register-to-vote' ` explaining

2024-04-12 14:12 UTC, travisbloom-cb commented on src/app/api/public/frames/register-to-vote/route.tsx
> +        partner: VerifiedSWCPartner.FARCASTER_FRAMES,
This is very different than a Verified SWC Partner and I'm concerned about comingling the logic. The key difference is that "verifiedSWCPartners" have permissioned access to make statements about metadata that we normally wouldnt trust (like whether an email address has be previously verified). 

If you'd like to reuse the logic, I'd prob decouple a lot of the logic in `verifiedSWCPartnersUserActionOptIn` into a "createOptInUserAction" utilitiy function that can be extended for this usecase, as well as called within verifiedSWCPartnersUserActionOptIn. You'll need additional props to fix the things like [this](https://github.com/Stand-With-Crypto/swc-web/blob/763-support-not-showing-text-for-email-your-rep-until-you-enter-your-address/src/data/verifiedSWCPartners/userActionOptIn.ts#L188)

2024-04-12 14:12 UTC, travisbloom-cb commented on src/app/api/public/frames/register-to-vote/route.tsx
> +        partner: VerifiedSWCPartner.FARCASTER_FRAMES,
We should also be screening against any verified crypto addresses here to see if the user exists

2024-04-12 14:12 UTC, travisbloom-cb commented on src/app/api/public/frames/register-to-vote/route.tsx
> +              ...frameData[frameIndex].buttons![0],
to improve type safety, I'd prob have a const for each frame so you can reference them directly instead of by array index and making unsafe type assertions.

2024-04-12 14:12 UTC, travisbloom-cb commented on src/app/api/public/frames/register-to-vote/route.tsx
> +        partner: VerifiedSWCPartner.FARCASTER_FRAMES,
Situation im thinking about:
A user has a SWC account with their email, but its not associated with their farcaster wallet. In this case, we might want to still allow them to mint to their farcaster address?

2024-04-12 14:12 UTC, travisbloom-cb commented on src/utils/server/thirdweb/erc721ClaimABI.ts
> +export const ERC_721_CONTRACT_ABI = [
I assume there's not a const we can import from TW here?

2024-04-12 14:12 UTC, travisbloom-cb commented on src/utils/server/verifiedSWCPartner/constants.ts
> +  [VerifiedSWCPartner.FARCASTER_FRAMES]: '', // No secret.
see my comment above about farcaster not being a verified SWC partner

2024-04-12 16:45 UTC, benson-budiman-cb commented on package.json
> +    "thirdweb": "^5.4.1",
Ya so this is actually thirdweb's new unified SDK - we should eventually migrate once we have time.

These docs have a cheatsheet to follow for the migration: https://portal.thirdweb.com/typescript/v5/migrate

2024-04-12 17:34 UTC, benson-budiman-cb commented on src/app/api/public/frames/register-to-vote/route.tsx
> +    input: {
Yeah, the default `usa.gov` link gets overwritten after the user inputs their state code. I will leave a comment.

2024-04-12 17:54 UTC, benson-budiman-cb commented on src/utils/server/thirdweb/erc721ClaimABI.ts
> +export const ERC_721_CONTRACT_ABI = [
As far as I can tell, there isn't a const from thirdweb. They also defined their own const In their own Farcaster Frames demo video.

2024-04-12 18:16 UTC, benson-budiman-cb commented on src/app/api/public/frames/register-to-vote/route.tsx
> +        partner: VerifiedSWCPartner.FARCASTER_FRAMES,
I see, the fact that it should be very different from the verified SWC partner flow signals to me that I should probably not reuse the logic at all. Let me just create a new helper function that is designed for frames.

2024-04-12 18:19 UTC, benson-budiman-cb commented on src/app/api/public/frames/register-to-vote/route.tsx
> +              ...frameData[frameIndex].buttons![0],
Good idea - I think having the individual frame constants will also make the code more readable.

2024-04-12 22:03 UTC, benson-budiman-cb commented on src/app/api/public/frames/register-to-vote/route.tsx
> +              ...frameData[frameIndex].buttons![0],
Albeit I do not think there is a way around using the bang (`!`) because the buttons field is optional for the FrameMetadata object.

2024-04-12 22:10 UTC, travisbloom-cb commented on src/app/api/public/frames/register-to-vote/route.tsx
> +              ...frameData[frameIndex].buttons![0],
Right, but the actual object you have doesnt have it as optional. You can change the type definition to `satisfies` instead of `as`, so your typechecking the object is the correct structure, but you have guarantees about the fields you know exist

2024-04-12 22:14 UTC, benson-budiman-cb commented on src/app/api/public/frames/register-to-vote/route.tsx
> +              ...frameData[frameIndex].buttons![0],
TIL `satisfies` vs `as`

2024-04-12 23:20 UTC, benson-budiman-cb commented
@travisbloom-cb I've updated the PR with your comments.

- The biggest change is related to the "external" user action opt-in flow. I create a new file that contains the main opt-in and upsert logic, updating the flow to provide the right flags based on the inputs and also to handle a crypto address input.
  - This new file is referenced by the existing verified partner flow and by the new frames flow.
- Regarding the ability for folks to re-mint to their own wallet address, see [this code pointer](https://github.com/Stand-With-Crypto/swc-web/pull/766/files#diff-817fb8ad5e3dc4b94cd0aab64dbe4cb927ca113b86bc1b713ce717875a8b2f27R497-R530).

I still have to make the design changes, so I am working on that.

2024-04-15 13:43 UTC, travisbloom-cb approved these changes
👏

2024-04-15 19:15 UTC, travisbloom-cb approved these changes

2024-04-15 19:20 UTC, lucasrmp-cb approved these changes

2024-04-15 19:20 UTC, lucasrmp-cb commented on package.json
> +    "@tanstack/react-query": "^5.29.0",
Time to migrate `swr` to `react-query`, what do you think @travisbloom-cb?

2024-04-15 19:26 UTC, merged