improve sign up flow with experiments
Stand-With-Crypto/swc-web pull request #829
Opened 2024-05-07 23:47 UTC by matheusmendes-cb

closes 
#727 
fixes 

## What changed? Why?

We are going to start an experiment in the signup flow:
- 50% of the users will get the NFT as soon as they login for the first time;
- 50% of the users are only going to get the NFT when they finish updating their profile with all fields required.

This PR creates the new `UpdateUserProfileForm` UI, implements a generic component to handle AB Testing with different UIs and implements the AB test logic to `triggerPostLoginUserActionSteps` and `actionUpdateUserProfile`.

## PlanetScale deploy request

## Notes to reviewers

## How has it been tested?

- [x] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-05-08 12:56 UTC, travisbloom-cb requested changes
Great work!

2024-05-08 12:56 UTC, travisbloom-cb commented on src/actions/actionUpdateUserProfile.ts
> +    log(`claimNFTAfterUpdateUserProfile: opt in user action don't exist`)
this should trigger a sentry error because it should never happen

2024-05-08 12:56 UTC, travisbloom-cb commented on src/components/ui/experimentsTesting/index.ts
> +function useABTesting<K extends Experiments>({ experimentName }: { experimentName: K }) {
np: maybe we call this `useExperimentName` for consistency?

2024-05-08 12:56 UTC, travisbloom-cb commented on src/components/ui/experimentsTesting/index.ts
> +  const ComponentToRender = variants.find(v => v.name === variant)?.component
potential bug here: if you exclude a variant.

Ideally we can change the type signature to error if they aren't included, maybe by changing the prop to a dict with all the variants as keys instead of array?

2024-05-08 12:56 UTC, travisbloom-cb commented on src/components/app/updateUserProfileForm/step1/variant.tsx
> +      : {
why isnt this null like the contorl?

2024-05-08 15:08 UTC, matheusmendes-cb commented on src/components/ui/experimentsTesting/index.ts
> +function useABTesting<K extends Experiments>({ experimentName }: { experimentName: K }) {
Fixed.

2024-05-08 15:10 UTC, matheusmendes-cb commented on src/components/app/updateUserProfileForm/step1/variant.tsx
> +      : {
Because address is not optional anymore, so the zod schema does not accept address as null.

2024-05-08 15:20 UTC, matheusmendes-cb commented on src/components/app/updateUserProfileForm/step1/index.tsx
> +  if (hasCompleteUserProfile(props.user)) return <Control {...props} />
I think this handles this case, because if the user falls into the `Control` experiment, it will always render the `Control` component, but if the user falls into the `Variant` experiment, it will only have the NFT if he completes his profile, no?

2024-05-08 15:26 UTC, matheusmendes-cb commented on src/actions/actionUpdateUserProfile.ts
> +    log(`claimNFTAfterUpdateUserProfile: opt in user action don't exist`)
Fixed

2024-05-08 16:06 UTC, matheusmendes-cb commented on src/components/ui/experimentsTesting/index.ts
> +  const ComponentToRender = variants.find(v => v.name === variant)?.component
Nice catch, fixed.

2024-05-08 16:48 UTC, travisbloom-cb commented on src/components/app/updateUserProfileForm/step1/index.tsx
> +  if (hasCompleteUserProfile(props.user)) return <Control {...props} />
no, currently we give the NFT as soon as the user signs up, regardless of whether they fill out their profile. Thats the change your making in this PR :(

2024-05-08 16:48 UTC, travisbloom-cb commented on src/components/app/updateUserProfileForm/step1/variant.tsx
> +      : {
Got it....my gut is that there's a subtle bug here somewhere but if we've sufficiently QAed the address feature is working than maybe it's fine. The form shows a "required" error if you submit w/o adding adding an address? Is the issue that the type definition for default values is wrong if its null? Because its fine of the submit fn expects it not to be null (it should catch and error in that case).

2024-05-08 16:48 UTC, travisbloom-cb commented on src/components/ui/googlePlacesSelect/index.tsx
> +          leftIcon={showIcon ? <MapPin className="h-4 w-4 text-gray-500" /> : undefined}
Synced w/ Mar, ignore my comment

2024-05-08 17:02 UTC, matheusmendes-cb commented on src/components/app/updateUserProfileForm/step1/index.tsx
> +  if (hasCompleteUserProfile(props.user)) return <Control {...props} />
Oh yeah, that's right, got it, gonna fix that.

2024-05-08 19:11 UTC, matheusmendes-cb commented on src/components/app/updateUserProfileForm/step1/variant.tsx
> +      : {
I check this case and it wasn't erroring because the address accepted empty strings so I fixed it and tested both cases. Control component allows the user to submit the form without address set, Variant component does not accept it.

2024-05-20 15:35 UTC, lucasrmp-cb approved these changes

2024-05-20 15:37 UTC, lucasrmp-cb commented
The github closing keyword should be in the same line as the link to the issue (`fixes #123` instead of `fixes\n#123`, this causes the PR to not be linked to the issue in the `development` section

2024-05-20 15:40 UTC, travisbloom-cb approved these changes

2024-05-21 19:24 UTC, travisbloom-cb submitted a review, later dismissed

2024-05-24 18:52 UTC, merged