Redirect to the profile update form after they log in on user deep link
Stand-With-Crypto/swc-web pull request #840
Opened 2024-05-09 19:56 UTC by matheusmendes-cb

closes 
#837 

fixes 

## What changed? Why?

To redirect the user back to the profile update form if we deep link a user to update their profile and they arent logged in we have to persist this data somewhere, in this case it was simpler to persist this queryParam on the URL, so now we redirect to the login url persisting the queryParam and once the user is authenticated, we get check if the user has the correct queryParam and if so, we redirect him back to the deep link url.

## Notes to reviewers

## How has it been tested?

- [x] Locally
- [x] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-05-09 20:52 UTC, travisbloom-cb requested changes

2024-05-09 20:52 UTC, travisbloom-cb commented on src/app/[locale]/(homepageDialogDeeplink)/action/sign-up/page.tsx
> +    queryParamKey: OPEN_UPDATE_USER_PROFILE_FORM_QUERY_PARAM_KEY,
Thoughts on this being generic so you can pass any arbirary redirect path you want here? Like `redirectAfterLogin=/foo/bar?baz=1`

2024-05-09 20:52 UTC, travisbloom-cb commented on src/types/index.ts
> +  searchParams?: { [key: string]: string | string[] | undefined }
TIL

2024-05-09 20:54 UTC, travisbloom-cb commented on src/app/[locale]/(homepageDialogDeeplink)/action/sign-up/page.tsx
> +    queryParamKey: OPEN_UPDATE_USER_PROFILE_FORM_QUERY_PARAM_KEY,
You need it to be generic to support the follow up ticket

2024-05-09 22:11 UTC, matheusmendes-cb commented on src/app/[locale]/(homepageDialogDeeplink)/action/sign-up/page.tsx
> +    queryParamKey: OPEN_UPDATE_USER_PROFILE_FORM_QUERY_PARAM_KEY,
Yes, I realized it after seeing the other ticket. Fixing it right now.

2024-05-10 12:44 UTC, travisbloom-cb requested changes

2024-05-10 12:44 UTC, travisbloom-cb commented on src/app/[locale]/(homepageDialogDeeplink)/action/sign-up/page.tsx
> +    return router.replace(urls[destination]())
can we gracefully fail/trigger sentry here?

2024-05-10 17:26 UTC, matheusmendes-cb commented on src/app/[locale]/(homepageDialogDeeplink)/action/sign-up/page.tsx
> +    return router.replace(urls[destination]())
Done

2024-05-10 17:53 UTC, travisbloom-cb requested changes

2024-05-10 17:53 UTC, travisbloom-cb commented on src/app/[locale]/(homepageDialogDeeplink)/action/sign-up/page.tsx
> +    if (!destination) {
the bug im looking to fix is what if there's a destination and its an invalid urls param. We actually dont wanna trigger sentry errors if the user doesnt pass destination

2024-05-10 20:44 UTC, matheusmendes-cb commented on src/app/[locale]/(homepageDialogDeeplink)/action/sign-up/page.tsx
> +    if (!destination) {
Fixed!

2024-05-14 14:20 UTC, travisbloom-cb approved these changes

2024-05-14 14:54 UTC, merged