Adds missing await statement
Stand-With-Crypto/swc-web pull request #904
Opened 2024-05-23 13:17 UTC by paulovictor-cb

## What changed? Why?

This PR adds await on createUserActionDonation call. 

## How has it been tested?

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-05-23 13:32 UTC, travisbloom-cb requested changes

2024-05-23 13:32 UTC, travisbloom-cb commented on src/utils/server/coinbaseCommerce/storePaymentRequest.ts
> +  const donationAction = await prismaClient.userAction.create({
This is the only place we need an await. You can safely return async promises from a fn without awaiting

2024-05-23 14:14 UTC, paulovictor-cb commented on src/utils/server/coinbaseCommerce/storePaymentRequest.ts
> +  const donationAction = await prismaClient.userAction.create({
Changed

2024-05-24 13:32 UTC, matheusmendes-cb approved these changes

2024-05-28 13:19 UTC, travisbloom-cb approved these changes

2024-05-28 13:49 UTC, merged