Update user action success screen
Stand-With-Crypto/swc-web pull request #918
Opened 2024-05-29 18:17 UTC by eduardopicolo-cb

closes #678 

## What changed? Why?

### Update post user action success screen and follow-up actions.

#### Sign-Up/Sign-In Prompt:
After completing an action, users will now be prompted to sign up/in. 

#### SMS Opt-In:
For users who haven't opted in to receive SMS notifications, a form will be displayed to provide their phone number.

#### Next actions:
Show a prioritized list of uncompleted actions.

## How has it been tested?

- [x] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-06-06 16:45 UTC, lucasrmp-cb requested changes

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/components/app/userActionFormSuccessScreen/index.tsx
> +      void performedActionsResponse.mutate()
Sounds like for me that invalidating the cache is the responsibility of the action form when they are created, not the action success screen. Can we change this so when we call the create action api we invalidate or update the cache?

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/components/app/userActionFormSuccessScreen/index.tsx
> +    if (fullProfileRequest.isLoading) {
I don't think we should be accessing this directly (more on a comment bellow), we should change this to use`session.isLoading` instead

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/components/app/userActionFormSuccessScreen/index.tsx
> +        '-mx-6 -mb-6 overflow-auto max-md:-mt-20 md:-mt-14 lg:max-h-[75vh]',
Same code smell here

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/components/app/userActionFormSuccessScreen/index.tsx
> +          void performedActionsResponse.mutate()
Exactly this, if a client action changes responses from api endpoints that we need the latest version, we should invalidate it's cache

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/hooks/useSession.ts
> +    fullProfileRequest,
I don't think we should return this, the hook returns session information and the full profile request status I don't see as part of it. Since we're using `useSWR` you could call `useApiResponseForUserFullProfileInfo` again where you need it, it shouldn't trigger another api call. And if the only thing you need is the `mutate` function you can use the global mutate passing the cache key to invalidate https://github.com/Stand-With-Crypto/swc-web/blob/a2dce55a9e2e288c138590b78309582370006a82/src/components/app/authentication/loginDialogWrapper.tsx#L213-L214

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/utils/shared/getUserActionsProgress.ts
> +  .map(([key, _]) => key)
Why all of this? A simple static array wouldn't be enough? Didn't find any reference of `USER_ACTIONS_AVAILABLE_FOR_CTA` to justify it's existence

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/components/app/userActionRowCTA/userActionRowCTAsList.tsx
> +            : 'incomplete'
np: can we refactor this to not have this nested ternary?

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/components/app/userActionRowCTA/userActionRowCTAsList.tsx
> +  render?: (props: React.ComponentPropsWithoutRef<typeof UserActionRowCTA>) => React.ReactNode
This should be a component, doing it like this you're removing a part of the lifecycle ou of it (see the 2 other comments bellow for the implementation)
```suggestion
  render?: React.ComponentType<React.ComponentPropsWithoutRef<typeof UserActionRowCTA>>
```

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/components/app/userActionRowCTA/userActionRowCTAsList.tsx
> +  render,
```suggestion
  render: Render,
```

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/components/app/userActionRowCTA/userActionRowCTAsList.tsx
> +          render({ state, ...props })
```suggestion
          <Render state={state} {...props} />
```

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/components/app/userActionRowCTA/index.tsx
> +            className="max-sm:hidden"
np: In other places we use the mobile first approach for this, we could unify it to the others
```suggestion
            className="hidden md:block"
```

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/components/app/userActionRowCTA/index.tsx
> +          <div className="relative flex h-[80px] w-[80px] flex-shrink-0 items-center justify-center overflow-hidden rounded-xl bg-black lg:h-[100px] lg:w-[100px]">
Is `relative` necessary?

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/components/app/userActionFormVoterRegistration/sections/success.tsx
> +            src="/actionTypeIcons/registerToVote.png"
Can we use sizes instead of fill here? Better for optimization

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/components/app/userActionFormVoterRegistration/index.tsx
> +import { getValues } from '@/utils/shared/getEntries'
I don't think these utils should exists and we shouldn't use them:
1. `Object.values`, `Object.entries` and `Object.keys` already are typesafe
2. The only thing these functions are doing is suppressing errors that we shouldn't want to suppress, this can cause errors impossible to identify bc nothing is being logged
3. Type safety in the reference object will never allow possibly undefined'ish values to be passed to a native call of `Object.values`

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/components/app/userActionFormVoterRegistration/sections/success.tsx
> +            fill
Same question of `fill` against `sizes` here

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/components/app/userActionRowCTA/index.tsx
> +            // Show on Mobile
Unnecessary comment

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/components/app/userActionRowCTA/index.tsx
> +            // Show on Desktop
Unnecessary comment

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/components/app/userActionRowCTA/index.tsx
> +            className="max-sm:hidden"
Same thing here, with the idea of mobile first would be better to do `block sm:hidden` here

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/components/app/userActionRowCTA/index.tsx
> +          <div className="max-sm:hidden">
+1

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/components/app/userActionFormSuccessScreen/smsOptIn.tsx
> +'use client'
Why is this a client component?

2024-06-06 16:45 UTC, lucasrmp-cb commented on src/components/app/userActionFormSuccessScreen/smsOptIn.tsx
> +    <div className="mx-auto flex h-full max-w-[60ch] flex-col items-center gap-6 text-center">
Instead of using literal values for everything in this cases we should try and use built in values for UI consistence, we should revisit this PR and take a look at which of these values are actually necessary to be a one-of

2024-06-06 18:54 UTC, eduardopicolo-cb commented on src/components/app/userActionFormJoinSWC/successDialog.tsx
> +            '-mx-6 -mb-6 overflow-auto max-md:-mt-20 md:-mt-14 lg:max-h-[75vh]',
Without negative margin the scrollbar looks like this 
![image](https://github.com/Stand-With-Crypto/swc-web/assets/167582510/2d348e73-f117-4747-b48b-4e32ee482b9e)

Or we could let it overflow the modal:
![image](https://github.com/Stand-With-Crypto/swc-web/assets/167582510/771e2b1d-5449-41af-b75f-d4bc4172d1ad)

2024-06-14 19:16 UTC, olavoparno commented on public/actionTypeIcons/call.png
hey man, why are we deleting the svg files? I think we use at `src/components/app/recentActivityRow/activityAvatar.tsx`, don't we?

I only caught that because I was using the same ones on the map feature, same ones from the homepage actions activity

2024-06-14 19:19 UTC, olavoparno commented on src/components/app/pageBillDetails/filters.tsx
> +export const STANCE_OPTIONS = ['All', ...Object.values(DTSI_BillPersonRelationshipType)] as const
why was getValues deleted? sorry, still getting acquainted to the codebase

2024-06-14 19:20 UTC, olavoparno commented on src/components/app/pageBillDetails/filters.tsx
> +export const STANCE_OPTIONS = ['All', ...Object.values(DTSI_BillPersonRelationshipType)] as const
oh, Object.values is generic now, is that it?

2024-06-14 19:21 UTC, eduardopicolo-cb commented on public/actionTypeIcons/call.png
The ones being used in the activity feed comes from `/public/activityFeedIcons`. 
The ones I deleted from `/public/actionTypeIcons` were not being used anywhere.

2024-06-14 19:23 UTC, olavoparno commented on public/actionTypeIcons/call.png
Right, my bad thank you

2024-06-14 19:25 UTC, olavoparno commented on src/components/app/userActionFormSuccessScreen/constants.ts
> +    title: 'You donated to help keep  crypto in America!',
double space between keep and crypto it seems

2024-06-14 19:25 UTC, eduardopicolo-cb commented on src/components/app/pageBillDetails/filters.tsx
> +export const STANCE_OPTIONS = ['All', ...Object.values(DTSI_BillPersonRelationshipType)] as const
Per Lucas request https://github.com/Stand-With-Crypto/swc-web/pull/918#discussion_r1629853196.

The util function could suppress errors and the return type is the same as Object.values.

2024-06-15 00:06 UTC, olavoparno submitted a review, later dismissed

2024-06-18 17:16 UTC, twistershark submitted a review, later dismissed

2024-06-19 13:19 UTC, twistershark submitted a review, later dismissed

2024-06-19 19:00 UTC, twistershark submitted a review, later dismissed

2024-06-20 20:39 UTC, twistershark approved these changes

2024-06-20 22:59 UTC, merged