feat: add advocates heatmap
Stand-With-Crypto/swc-web pull request #968
Opened 2024-06-13 17:11 UTC by olavoparno

closes 

fixes 

## What changed? Why?

- it adds a normal route under [locale] and a standalone outside of it, without header and footer.
- renders the total number of advocates in the US into each state.
- the map renders dots according to actions being fetch on the go and larger dots for the states with more advocates.

#### routes:
1. /map
2. /embedded/map/[topStatesLimit]

## PlanetScale deploy request

## Notes to reviewers

## How has it been tested?

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

2024-06-14 13:19 UTC, lucasrmp-cb commented
We're missing the reference to the issue here

2024-06-14 13:25 UTC, olavoparno commented
> We're missing the reference to the issue here

thanks, I've just added in the PR description.

2024-06-14 14:09 UTC, lucasrmp-cb requested changes
Good job, will need a second pass but there's a few points to take a look already

2024-06-14 14:09 UTC, lucasrmp-cb commented on src/app/embedded/map/[topStatesLimit]/page.tsx
> +    <AdvocatesHeatmap
I have an issue with naming on this page, you have this following component tree
```
MapPage
|    AdvocatesHeatmap
|    |    PageTitle
|    |    PageSubTitle
|    |    AdvocateHeatmapCounter
|    |    RenderMap
```

The problem here is a separation of concerns issue because:
- `AdvocatesHeatmap` is actually the whole page content and we have a naming convention for this page components where we have the prefix "page" followed by the page name, so `pageAdvocatesHeatmap` would be more appropriate
- `RenderMap` is not as generic as the name suggests, a better name for it would be `AdvocatesHeatmap`, since it only renders the US map with required props called `getTotalAdvocatesPerState` and `topStateMarkers` which closely relates it to this specific use case

That said I think a more coherent naming component tree would look something like this:

```
EmbeddedMapPage
|    AdvocatesHeatmapPage (defined in `src/components/app/pageAdvocatesHeatmap`)
|   |    PageTitle
|   |    PageSubTitle
|   |    AdvocateHeatmapCounter
|   |    AdvocatesHeatmap (does the same thing that `RenderMap` currently does)
```

2024-06-14 14:09 UTC, lucasrmp-cb commented on src/components/app/advocatesHeatmap/advocateHeatmapCounter.tsx
> +    count: roundDownNumberToAnimateIn(initial.countUsers.count, 100),
np: I think we should think about rounding down a percentage of the count instead of a specific value, we have more than 1MM advocates, animating the last digits only doesn't look all that great to me

2024-06-14 14:09 UTC, lucasrmp-cb commented on src/components/app/advocatesHeatmap/advocateHeatmapCounter.tsx
> +        className={odometerStyles.odometerSatoshi}
I don't think the css module should be an api for the references to mess with, does just passing `font-sans` here and applying it with `cn` inside the odometer work?

2024-06-14 14:09 UTC, lucasrmp-cb commented on src/components/app/advocatesHeatmap/advocatesHeatmap.tsx
> +  )
Again, isn't there a way to move this processing server side?

2024-06-14 16:35 UTC, olavoparno commented on src/components/app/advocatesHeatmap/advocateHeatmapCounter.tsx
> +        className={odometerStyles.odometerSatoshi}
I've added to it because font-family is applied to a span inside an H1, it's not on the top level of the component tree

2024-06-17 12:40 UTC, olavoparno commented on src/app/api/public/advocates-map/total-advocates-per-state/[topStatesLimit]/route.ts
> +}
we need it as lively as possible to show on monitors at conferences

2024-06-17 14:06 UTC, lucasrmp-cb reviewed
We spoke on DMs about the json file stuff, lmk when we have a decision on that pls

2024-06-17 14:06 UTC, lucasrmp-cb commented on src/app/embedded/map/[topStatesLimit]/page.tsx
> +  // redirects to not found in case of invalid topStatesLimit
I think your code bellow is pretty clear, don't think this is necessary

2024-06-17 14:15 UTC, travisbloom-cb approved these changes

2024-06-17 14:15 UTC, travisbloom-cb commented on src/components/app/pageAdvocatesHeatmap/advocatesHeatmapPage.tsx
> +  const totalAdvocatesPerState = useMemo(
we shouldnt use useMemo unless we're actually doing something computationally complex

2024-06-17 14:15 UTC, travisbloom-cb commented on src/utils/server/metadataUtils.ts
> +    metadataBase: new URL('https://www.standwithcrypto.org'),
I dont think we want these spread across all pages, just the two top level layouts. maybe have a `const TOP_LEVEL_METADATA_DETAILS` const that gets exported from this file and used in the two top levels?

2024-06-17 20:07 UTC, lucasrmp-cb approved these changes

2024-06-17 20:17 UTC, merged